### ISSUE TITLE
Error when changing tabs

### ISSUE THREAD

**Issue by MartinRyx** [BIDeveloperExtensions/bideveloperextensions#100]
Since upgrading to latest version (2.3.8) both me and my colleague gets the following error every now and then:
```
Unable to cast object of type 'Microsoft.DataTransformationServices.Design.DtsPackageView' to type 'Microsoft.DataWarehouse.Design.EditorWindow'.
   at BIDSHelper.SSIS.ParametersWindowPlugin.OnWindowActivated(Window GotFocus, Window LostFocus) in C:\projects\BIDS Helper\GitHub\bideveloperextensions2\SSIS\ParametersWindowPlugin.cs:line 69
```

The last time it happened after right-click on a package in Solution Explorer and clicked _Execute Package_ on an SSIS package. Sometimes it happens when changing tabs between packages.

**Version**
![image](https://user-images.githubusercontent.com/9428639/84895646-ec11c700-b0a2-11ea-9180-ac6d1f8ca618.png)

**Comment by furmangg** [comment]
Looks like your SSIS extension version is quite a bit behind. I would follow the instructions here to uninstall the SSAS and SSRS extensions then run the latest SSDT installer:
https://docs.microsoft.com/en-us/sql/ssdt/download-sql-server-data-tools-ssdt?view=sql-server-ver15#ssdt-for-vs-2017-standalone-installer

Let us know if that solves the problem once your version screen shows SSIS 2.4 or higher. Right now yours is showing SSIS 2.1
