### ISSUE TITLE
BIDS Helper commands not showing up in VS 2019 Coomunity Edition

### ISSUE THREAD

**Issue by bluestar5000** [BIDeveloperExtensions/bideveloperextensions#101]
We have Visual Studio Community 2019 and I installed the various BI Extensions including Analysis Services.

When I installed BIDS Helper in prior versions, the BID Helper commands showed up in the context menu selection within an Analysis Services (Multidimensional) project. However, when I installed, BI Developer Extensions for Visual Studio 2019, none of the BIDS Helper commands are visible. I have confirmed that BI Developer Extensions for Visual Studio 2019 is installed because it appears in the Options – BIDS Helper section. 

Is there a way to show the BIDS Helper commands on the right click menus?

**Comment by furmangg** [comment]
Can you go to Tools... Options... BIDS Helper and post a screenshot of the Version tab?

Did you right click and wait 30 seconds and right-click again? BI Developer Extensions Loads asynchronously now so sometimes there is a delay.

**Comment by bluestar5000** [comment]
Greg,

Please see attached screenshots of version and features page. It must have been the delay. I see some of the BIDS Helper features now within the context menu.

Thank you.

David

[cid:image001.png@01D648D3.5F5629F0]

[cid:image002.png@01D648D3.A25EF600]
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by furmangg** [comment]
Your email reply attachments didn’t come through. Please view the issue online and upload your images there.

**Comment by furmangg** [comment]
I'm going to close this issue due to lack of response. We just released a new 2.3.9 version you might also try. If it's still a problem please provide the info requested above via website uploads (not email attachments)
