### ISSUE TITLE
Datatools 2017 - No SSAS features available

### ISSUE THREAD

**Issue by ArminFri** [BIDeveloperExtensions/bideveloperextensions#102]
Installed Extensions in Datatools. I need to design aggregations in SSAS.

**Version**
![image](https://user-images.githubusercontent.com/28890858/89014289-a12bd600-d315-11ea-81ef-f4f0358dfb75.png)
SSAS Version:
![image](https://user-images.githubusercontent.com/28890858/89014339-af79f200-d315-11ea-9c02-ea7bfc54f6fc.png)

Note:
SSIS Extensions like Batch Property Update and so on are still working.

Datatools Infos:
![image](https://user-images.githubusercontent.com/28890858/89017603-dbe43d00-d31a-11ea-9f01-2d57b93523b1.png)

**Comment by furmangg** [comment]
We just released BI Developer Extensions v2.3.9 which should fix compatibility issues. Please try that (or wait for it to auto-update) and let me know.
