### ISSUE TITLE
'Unable to cast object' error when opening or switching to SSIS window

### ISSUE THREAD

**Issue by kendalllister** [BIDeveloperExtensions/bideveloperextensions#112]
Whenever I open a .dtsx file in Visual Studio, or switch to an open file, and when I click on an element for the first time, I get an error:

![image](https://user-images.githubusercontent.com/7309079/92431161-1f637e00-f1da-11ea-947d-472b56f9fa66.png)

I'm using Visual Studio 2017 and I believe I have the latest version of BI Developer Extensions and the SSDT extensions:

![image](https://user-images.githubusercontent.com/7309079/92431269-6c475480-f1da-11ea-9556-19c3bfab70a4.png)

I'm not sure what other details would be helpful, but I'm happy to supply whatever would assist in debugging this issue.

**Comment by dgosbell** [comment]
Your version of the SSIS extension is a bit behind. To run the 2.4 version of BI Dev Extensions you need at least v2.7 of the SSIS extension. At the bottom of our [downloads page](https://bideveloperextensions.github.io/downloads/) is a table listing the different version. You'll either need to update SSIS or use an older version of BI Developer Extensions.

**Comment by kendalllister** [comment]
Thanks, Darren, that seems to have been the problem - I had checked all the versions but must have missed that one. Sorry to have wasted your time.

**Comment by dgosbell** [comment]
No worries, with the way the updates trickle out at different times for the different components it's hard for all of us to keep up. SSIS is particularly bad because it has external dependencies which requires a completely separate installer

**Comment by kendalllister** [comment]
That was my problem - I hadn’t realised SSIS can’t be updated by Visual Studio, so although I apply updates as they appear, it was drifting out of date. Thanks for BIDS - it’s already found some invalid things in my cubes.
