### ISSUE TITLE
after Windows Update the BI Dev Extension doesn't open SSIS-Projects: incompatible

### ISSUE THREAD

**Issue by schneiderOSP** [BIDeveloperExtensions/bideveloperextensions#118]
**Describe the bug**
SSIS-Projects not listet, only the solution indicates: incompatible

**Version**
Take a screenshot of the Tools... Options... BIDS Helper... Version screen and post it here.

**To Reproduce**
after Windows Update:
opened VS 2019
connected to the git repo
opened the file folder containing my SSIS solution
opened the solution:
solution is visible, but only collapsed with notice: incompatible

**Expected behavior**
I can expand the solution and see projects and items like .dtsx-Packages

**Screenshots**
![grafik](https://user-images.githubusercontent.com/48918028/100766989-89ff1100-33f9-11eb-8d91-1b842b1e3ab7.png)

**Additional context**
Windows Update started working, so I gave it to update my PC. This seemed to make either VS2019 incombatible with BI Dev Ext or the other way around

**Comment by furmangg** [comment]
I don’t think this is a BI Developer Extensions issue. I would go to Extensions... Manage Extensions and ensure the SQL Server Integration Services Projexta extension is installed and updated to the latest which is 3.1 currently.

**Comment by schneiderOSP** [comment]
Yes, but updating of SQL Server Integration Services Projects extension didn't work. So I had to reinstall the complete VS 2019. It working before of a Windows Update, so it seems that also BI Developer Extensions got an update, but without some checks if the new version fits to the currently installed VS2019. Nevertheless, thank you for the fast feedback :-)

**Comment by dgosbell** [comment]
> so it seems that also BI Developer Extensions got an update, but without some checks if the new version fits to the currently installed VS2019

No, this is not the case in this situation. We do not generate the "(incompatible)" tag next to a project name, that is Microsoft doing that. So it's either an issue with VS2019 or the SSIS project extensions.
