### ISSUE TITLE
BIDS Helper encountered an error when Visual Studio started

### ISSUE THREAD

**Issue by Laminaat** [BIDeveloperExtensions/bideveloperextensions#119]
**Describe the bug**
When working with a SSAS Tabular cube I noticed some functionality of BIDS Helper wasn't working anymore for me. I couldn't work with Tabular Display Folders. In the end I updated Visual Studio (Microsoft Visual Studio Community 2019 Version 16.8.3) and all underlying components of BIDS helper, as well as BIDS helper itself (which is the situation in the screenshots below). But the errors remained exactly the same.

I noticed that my SSDTBI Build version number was higher then what I saw in other issues posted here. But I'm not sure if this is related to my problem.

**Version**
![afbeelding](https://user-images.githubusercontent.com/18725570/102216460-74024d80-3edb-11eb-956a-782f275c094c.png)

**To Reproduce**
1. Go to Model.bim (SSAS Tabular cube)
2. Right Click on the Model.bim and click 'Tabular Display Folders'
3. See error

**Expected behavior**
Normally I could edit the Display Folders.

**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/18725570/102216785-f68b0d00-3edb-11eb-98e8-3bf7377bf052.png)

**Note**
I will gladly provide any extra information that might be necessary!

**Comment by Laminaat** [comment]
I found a simple workaround for this issue. The culprit seems to be the newest version of the Visual Studio extension: Microsoft Analysis Services Projects. [Here ](https://marketplace.visualstudio.com/items?itemName=ProBITools.MicrosoftAnalysisServicesModelingProjects) you can find a download to revert back from 2.9.15 to 2.9.14. 

The mantra of sticking with old software versions that you know that work instead of the latest and 'greatest' seems to hold true  yet again when working with SQL and SSAS. 🤔 FYI, it is possible to disable auto update on Visual Studio extensions. Which I will do for now so that I can keep working.

**Comment by furmangg** [comment]
We've published an [updated release](https://github.com/BIDeveloperExtensions/bideveloperextensions/releases/tag/v2.4.1) of BI Developer Extensions for Visual Studio 2019 that resolves this issue. Please note the compatible SSAS extension version.
