### ISSUE TITLE
Printer Friendly Dimension Usage - Object not set to an instance of an object

### ISSUE THREAD

**Issue by DAZCUK46** [BIDeveloperExtensions/bideveloperextensions#120]
Receive error message when selecting "Printer Friendly Dimension Usage..."
![image](https://user-images.githubusercontent.com/29930723/110348560-b1353200-8029-11eb-8730-827c7ee7652d.png)

Version
VS2019 Professional: 16.5.0
MS Analysis Services Projects: 2.9.15
BI Developer Extensions for Visual Studio 2019: 2.4.0

**Comment by furmangg** [comment]
We've published an [updated release](https://github.com/BIDeveloperExtensions/bideveloperextensions/releases/tag/v2.4.1) of BI Developer Extensions for Visual Studio 2019 that resolves this issue. Please note the compatible SSAS extension version.
