### ISSUE TITLE
BIDS Helper encountered an error when Visual Studio started after update

### ISSUE THREAD

**Issue by DominiqueFr10** [BIDeveloperExtensions/bideveloperextensions#123]
After installing the latest update of Visual Studio, the following error occurs
![image](https://user-images.githubusercontent.com/70959714/114589177-b8cea300-9c87-11eb-901e-b67d6cafc6d9.png)
BIDS Helper encountered an error when Visual Studio started:
BIDS Helper encountered an error when Visual Studio started:
BIDS Helper plugin constructor failed on TriStatePerspectivesPlugin: Une exception a été levée par la cible d'un appel.
   à System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   à System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   à BIDSHelper.BIDSHelperPackage.OriginalInitialize() dans C:\projects\BIDS Helper\GitHub\bideveloperextensions2\BidsHelperPackage.cs:ligne 341

Inner exception:
Une exception a été levée par la cible d'un appel.
   à System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   à System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   à BIDSHelper.BIDSHelperPackage.OriginalInitialize() dans C:\projects\BIDS Helper\GitHub\bideveloperextensions2\BidsHelperPackage.cs:ligne 341
Inner exception:
Méthode introuvable : 'Void Microsoft.AnalysisServices.Design.Scripts..ctor(Microsoft.AnalysisServices.Cube)'.
   à BIDSHelper.BIDSHelperWindowActivatedPluginBase.OnEnable() dans C:\projects\BIDS Helper\GitHub\bideveloperextensions2\Core\BIDSHelperWindowActivatedPluginBase.cs:ligne 112
   à BIDSHelper.Core.BIDSHelperPluginBase..ctor(BIDSHelperPackage package) dans C:\projects\BIDS Helper\GitHub\bideveloperextensions2\Core\BIDSHelperPluginBase.cs:ligne 47
   à BIDSHelper.TriStatePerspectivesPlugin..ctor(BIDSHelperPackage package) dans C:\projects\BIDS Helper\GitHub\bideveloperextensions2\SSAS\TriStatePerspectivesPlugin.cs:ligne 40

**Comment by AnzeOrehek** [comment]
Did you find the solution, because I have the same problems after VS2019 update?

**Comment by DominiqueFr10** [comment]
no unfortunately

**Comment by furmangg** [comment]
We've published an [updated release](https://github.com/BIDeveloperExtensions/bideveloperextensions/releases/tag/v2.4.1) of BI Developer Extensions for Visual Studio 2019 that resolves this issue. Please note the compatible SSAS/SSIS/SSRS extension version.
