### ISSUE TITLE
Expression window does not work

### ISSUE THREAD

**Issue by pablolerner** [BIDeveloperExtensions/bideveloperextensions#124]
**Describe the bug**
The expressions window looks transluscent and does not work

**Version**
![BIDS Helper Version](https://user-images.githubusercontent.com/75140839/115731157-492e7700-a35d-11eb-9138-cb09fb198307.png)

**To Reproduce**
1. Open any SSIS package
2. Click on Vew -> Other Windows -> Expression List (BIDS Helper)
3. See Error in the attached screen shot
![BIDS Helper Error](https://user-images.githubusercontent.com/75140839/115731720-be9a4780-a35d-11eb-917b-414328607517.png)

**Expected behavior**
The Expressions List shows all expressions in the package and looks like the screenshot in the documentation.
https://bideveloperextensions.github.io/features/ExpressionList/

**Comment by furmangg** [comment]
We've published an [updated release](https://github.com/BIDeveloperExtensions/bideveloperextensions/releases/tag/v2.4.1) of BI Developer Extensions for Visual Studio 2019 that resolves this issue. Please note the compatible SSIS extension version. 

Note that I did notice some flakiness in the Expressions window during my testing. Closing the Expressions window, clicking onto an SSIS package, then reopening the Expressions window (or worst case restarting Visual Studio) usually resolved the issue. Let me know if the new version plus these suggestions don't help you.
