### ISSUE TITLE
Method not found exception - VS 2019 - SQL Server 2019

### ISSUE THREAD

**Issue by bsaglamtimur** [BIDeveloperExtensions/bideveloperextensions#125]
When selecting

- Roles report
- Unused columns report
- Used columns report

I am having 
"Method not found" exception as seen below
![image](https://user-images.githubusercontent.com/84310397/118604852-4ee17600-b7be-11eb-8c84-5be064f78d73.png)

My version info

![image](https://user-images.githubusercontent.com/84310397/118605121-9831c580-b7be-11eb-89ed-3c52ec467ca0.png)

Printer friendly dimensions usage works fine

I have uninstalled and reinstalled SSAS, SSIS, SSRS and Bi Developer Extensions, nothing changed.

**Comment by furmangg** [comment]
We've published an [updated release](https://github.com/BIDeveloperExtensions/bideveloperextensions/releases/tag/v2.4.1) of BI Developer Extensions for Visual Studio 2019 that resolves this issue. Please note the compatible SSAS extension version.
