### ISSUE TITLE
Roles Report is not offered

### ISSUE THREAD

**Issue by RyoSaeba13** [BIDeveloperExtensions/bideveloperextensions#127]
**Describe the bug**
I open Visual Studio and connect to a SSAS Database. After I open the folder with the roles in the solution and right-click on the folder 'Roles' (I have opened the node with the many roles before). No context menu with "Roles Report ..." appears. Only 'New Role'.

In Visual Studio 2010 it worked pretty well.

**Version**
Take a screenshot of the Tools... Options... BIDS Helper... Version screen and post it here.

Microsoft Visual Studio Community 2019 - Version 16.9.3
BI Developer Extensions v2.4.0 for Visual Studio 2019 - An add-in to extend SQL Server Data Tools

**To Reproduce**

see above

**Expected behavior**

When I right-click on the folder "Roles" (while connected to a SSAS database) the context menu should offer me "Roles Report ..." as I know it from previous versions.

**Screenshots**

**Additional context**

"Roles Report" is activated in Options

**Comment by magnusmp** [comment]
I have the same issue. 
My Analysis Services Project version is 2.9,17 
Bids version 2.4.0

My Versions from the about box
Microsoft Visual Studio Community 2019
Version 16.10.3
VisualStudio.16.Release/16.10.3+31424.327
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Community

Microsoft Visual Studio Tools for Applications 2019   00435-60000-00000-AA972
Microsoft Visual Studio Tools for Applications 2019

Visual C++ 2019   00435-60000-00000-AA972
Microsoft Visual C++ 2019

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   16.10.526.50910
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.10.526.50910
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.10.526.50910
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.6.3000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Stream Analytics Tools for Visual Studio   2.6.3000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

BI Developer Extensions for Visual Studio 2019   2.4.0
BI Developer Extensions v2.4.0 for Visual Studio 2019 - An add-in to extend SQL Server Data Tools

C# Tools   3.10.0-4.21318.11+7ceb633154acb9d716fd3eb2b6df1a0468d8e416
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

GitHub.VisualStudio   2.11.106.19330
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

Microsoft Azure HDInsight Azure Node   2.6.3000.0
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.6.3000.0
Language service for Hive query

Microsoft Azure Stream Analytics Language Service   2.6.3000.0
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.40423.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.2
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   5.10.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Office Developer Tools for Visual Studio   16.0.31130.00
Microsoft Office Developer Tools for Visual Studio

Project   1.0
Information about my package

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Razor (ASP.NET Core)   16.1.0.2122504+13c05c96ea6bdbe550bd88b0bf6cdddf8cde1725
Provides languages services for ASP.NET Core Razor.

SQL Server Analysis Services   15.0.19526.0
Microsoft SQL Server Analysis Services Designer 
Version 15.0.19526.0

SQL Server Data Tools   16.0.62106.24090
Microsoft SQL Server Data Tools

SQL Server Integration Services   15.0.2000.167
Microsoft SQL Server Integration Services Designer
Version 15.0.2000.167

SQL Server Reporting Services   15.0.19528.0
Microsoft SQL Server Reporting Services Designers 
Version 15.0.19528.0

SsmsVsIntegration   1.0
Information about my package

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   16.0.30429.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.10.0-4.21318.11+7ceb633154acb9d716fd3eb2b6df1a0468d8e416
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Workflow Manager Tools 1.0   1.0

**Comment by furmangg** [comment]
We've published an [updated release](https://github.com/BIDeveloperExtensions/bideveloperextensions/releases/tag/v2.4.1) of BI Developer Extensions for Visual Studio 2019 that resolves this issue. Please note the compatible SSAS extension version.
