### ISSUE TITLE
VS2019 and SSAS "Deploy MDX Script" error

### ISSUE THREAD

**Issue by ScottKaysee** [BIDeveloperExtensions/bideveloperextensions#128]
Versions:
- Visual Studio 2019 (Version 16.8.7).
- Microsoft SQL Server Analysis Services Designer - Version 15.0.19526.0.
- BI Developer Extensions v2.4.0 for Visual Studio 2019

Added a few new Calculated Members to an existing Cube. Syntax is successful. Select "Deploy MDX Script" and the following error occurs:

![image](https://user-images.githubusercontent.com/40222404/132626810-6a4e008c-5205-431e-8459-359a1534f4b8.png)

**Version**
![image](https://user-images.githubusercontent.com/40222404/132627070-4083bbdd-0f80-4cc6-9216-efeed476534c.png)

**Additional context**
Hasn't been working since we upgraded to SQL Server 2019 and Visual Studio 2019 in May 2021. Might be related to the method external consultant used to apply the upgrade.

Thanks
Scott

**Comment by furmangg** [comment]
We've published an [updated release](https://github.com/BIDeveloperExtensions/bideveloperextensions/releases/tag/v2.4.1) of BI Developer Extensions for Visual Studio 2019 that resolves this issue. Please note the compatible SSAS extension version.
