### ISSUE TITLE
sync descriptions error - method not found

### ISSUE THREAD

**Issue by aisbergde** [BIDeveloperExtensions/bideveloperextensions#129]
**Describe the bug**
When I try "sync descriptions" I get this error:
![image](https://user-images.githubusercontent.com/9020187/133155912-c7ce7045-e7c6-481d-8c81-bf98260c15a4.png)

**Version**
![image](https://user-images.githubusercontent.com/9020187/133156043-eb228d7b-34e4-4b9e-a974-4b0defd1ffac.png)

**To Reproduce**
open a model in diagram view
click on any table
select sync descriptions
get the error

**Expected behavior**
it should be possible to sync the description

**Screenshots**

**Additional context**
Compatibilty level
SQL Server 2017 / Azure Analysis Services (1400)

Connection String
Provider=MSOLEDBSQL.1;Data Source=localhost\sql2019;Integrated Security=SSPI;Initial Catalog=EventAnalytics_2

**Comment by furmangg** [comment]
We've published an [updated release](https://github.com/BIDeveloperExtensions/bideveloperextensions/releases/tag/v2.4.1) of BI Developer Extensions for Visual Studio 2019 that resolves this issue. Please note the compatible SSAS extension version.
