### ISSUE TITLE
Update Estimated Counts Missing Again

### ISSUE THREAD

**Issue by stelth240** [BIDeveloperExtensions/bideveloperextensions#131]
**Describe the bug**
The Update Estimated Counts button on the partitions tab no longer appears. 

**Version**
![image](https://user-images.githubusercontent.com/11980837/141387129-b87109a1-1f63-4186-b0c7-3a964c06321a.png)

**To Reproduce**
1. Double-click on the Cube to open the designer.
2. Click the Partitions tab.
3. No BI Developer Extensions buttons are visible in the toolbar.

**Screenshots**
![image](https://user-images.githubusercontent.com/11980837/141387272-8542f976-eea8-49df-9612-143f1a1151f5.png)

**Additional context**
I also attempted to turn the setting off and back on in the options screen, and that did not help as well. All the settings in that page are set to True, and as far as I can tell, all the other features are working as expected.

Thank you!

**Comment by furmangg** [comment]
We've published an [updated release](https://github.com/BIDeveloperExtensions/bideveloperextensions/releases/tag/v2.4.1) of BI Developer Extensions for Visual Studio 2019 that resolves this issue. Please note the compatible SSAS extension version.
