### ISSUE TITLE
Expression Editor pops up when accessing the variable window description field.

### ISSUE THREAD

**Issue by AmcAmx69** [BIDeveloperExtensions/bideveloperextensions#134]
Describe the bug
The Expression Editor pops up when clicking on the description textbox of the variable window.
Version
 
![image](https://user-images.githubusercontent.com/67134205/166717353-a82f245b-77ee-485b-a5b7-5a5f1e7a313b.png)

To Reproduce
1.	Open an SSIS package.
2.	Open the variables window.
3.	Click on the Variable Grid Options button
 
![image](https://user-images.githubusercontent.com/67134205/166717392-a0e64052-e681-482f-854b-6fc0f49638d0.png)

4.	Select the following check boxes (see image below): 
a)	Raise event when variable value changes
b)	Description
5.	Uncheck box next to Expression
6.	Click <OK>
 
![image](https://user-images.githubusercontent.com/67134205/166717440-d4c30836-ac63-4a59-9d47-317c854d2399.png)

7.	Now click on the DESCRIPTION textbox in the Variables window to enter the variable description.
 
![image](https://user-images.githubusercontent.com/67134205/166717475-6f3358bc-286f-4013-a829-f3abdffba54b.png)

8.	This causes the Expression Editor to pop up.

![image](https://user-images.githubusercontent.com/67134205/166717539-df07aa8b-831f-4a74-82ab-1cd523b20354.png)

Expected behavior
The Expression Editor should not pop-up. This should place me into the Description field so that I can either edit or add text.
  
![image](https://user-images.githubusercontent.com/67134205/166717609-f42c27ef-4752-442d-8d5a-c6f3cbe75e28.png)

**Comment by furmangg** [comment]
Great catch! We've published an [updated release](https://github.com/BIDeveloperExtensions/bideveloperextensions/releases/tag/v2.4.1) of BI Developer Extensions for Visual Studio 2019 that resolves this issue. If you choose different columns to be visible, it pays attention to which columns are visible. Please note the compatible SSIS extension version.
