### ISSUE TITLE
Extension not loading in VS 2019 after install

### ISSUE THREAD

**Issue by ptreston** [BIDeveloperExtensions/bideveloperextensions#135]
**Describe the bug**
I have installed the extension via the manage extensions menu, closed and restarted Visual Studio, but in Tabular models I am not seeing any additional menu items.

**Version**
![image](https://user-images.githubusercontent.com/32093107/174479202-60cc2a0c-a706-41c9-99df-2381577b99d6.png)

**To Reproduce**

**Expected behavior**
Extension not loading

**Screenshots**
See above error captured in version window

**Additional context**
n/a

**Comment by furmangg** [comment]
We've published an [updated release](https://github.com/BIDeveloperExtensions/bideveloperextensions/releases/tag/v2.4.1) of BI Developer Extensions for Visual Studio 2019 that resolves this issue.
