### ISSUE TITLE
Variables Window Extensions Not Visible

### ISSUE THREAD

**Issue by ghost** [BIDeveloperExtensions/bideveloperextensions#136]
Using this version of BI Developer Extensions with Visual Studio and the Variables window extensions are not visible.  

![image](https://user-images.githubusercontent.com/18312540/176881282-ad338fa6-0557-4635-a620-0a45bfc4331e.png)

Uninstalling and reinstalling the extension does not resolve the issue.  Disabling/Enabling the option in Tools -> Options -> BIDS Helper -> Features -> Variables Window Extensions does not resolve the issue.  However, the Parameter Window Extensions are visible.

![image](https://user-images.githubusercontent.com/18312540/176881904-1efdebb8-a400-43c5-88d5-155abbfbf561.png)

**Comment by christiant79** [comment]
Same with us after installing the newest version of the Integration Services extension:
Microsoft SQL Server Integration Services Designer Version 16.0.845.0
Microsoft Visual Studio Community 2019 Version 16.11.18
VisualStudio.16.Release/16.11.18+32802.440
BI Developer Extensions for Visual Studio 2019   2.4.0
SQL Server Analysis Services   15.0.19623.0
SQL Server Data Tools   16.0.62205.05200
SQL Server Integration Services   16.0.845.0
SQL Server Reporting Services   15.0.19528.0

Downgrade SQL Server Integration Services Projects from 4.2 to 3.16 fixes the issue

**Comment by riftware** [comment]
Will there be a patch expected to support this?  Its amazing how painful the loss is in terms of comfort developing.  Unfortunately downgrading isn't an option for us at our company.

**Comment by furmangg** [comment]
We've published an [updated release](https://github.com/BIDeveloperExtensions/bideveloperextensions/releases/tag/v2.4.1) of BI Developer Extensions for Visual Studio 2019 that resolves this issue. Please note the compatible SSIS extension version. Thanks for your patience!
