### ISSUE TITLE
"Deploy Mdx Script" fails because assembly for Microsoft.AnalysisServices.Design can't be loaded

### ISSUE THREAD

**Issue by kaisp84** [BIDeveloperExtensions/bideveloperextensions#137]
"Deploy Mdx Script" does not work with Visual Studio 2019 (16.11.20) and Analysis Services Project extension (2.9.18) and BIDeveloperExtensions for Visual Studio 2019 (2.4.0) because assembly Microsoft.AnalysisServices.Design can't be loaded in Version 15.14.0.0. I assume that BIDeveloperExtension version 2.4.0 requires an old version of the assembly and Analysis Services Project extension (2.9.18) ships with a newer version. Is there a fix to allow BIDeveloperExtension to load the latest version of the assembly or can we update the extension with the new version? Screenshot of the error message is attached below.

More version infos:

Microsoft Visual Studio Enterprise 2019
Version 16.11.20
VisualStudio.16.Release/16.11.20+32929.386
Microsoft .NET Framework
Version 4.8.04084

SQL Server Analysis Services   15.0.19623.0
Microsoft SQL Server Analysis Services Designer 
Version 15.0.19623.0

**Version**
![BIDeveloperExtension_Version](https://user-images.githubusercontent.com/20833767/202414723-42502e4e-66b9-46b3-abea-7f2e6de3e831.PNG)

**To Reproduce**
1. Go to Multidimensional SSAS project in Visual Studio
2. Right click on Cube (.cube item in Cubes folder)
3. Select "Deploy MDX Script"
4. Error Dialog is displayed

**Expected behavior**
MDX Script will successfully get deployed to server

**Screenshots**
![BIDeveloperExtension_ErrorMessage](https://user-images.githubusercontent.com/20833767/202415112-3d8b1507-5beb-4093-b49f-f6bcf1869e49.PNG)

**Additional context**

**Comment by kaisp84** [comment]
I checked the version of Microsoft.AnalysisServices.Design.dll in directory C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\SSIS\160\BIShared on my machine and compared it to the version of Microsoft.AnalysisServices.Design.dll in bideveloperextensions\DLLs\SQL2019\Reference source code with ILDASM. 

Source Code: 15.14.0.0
Local Installation: 16.2.0.0

**Comment by cbracht** [comment]
Hello, our developers have the same issue with updated visual studio 2019 and BI Developer Extension 2.4.0 when trying to deploy MDX cube script

![image](https://user-images.githubusercontent.com/1489764/205029226-23466fb8-b81b-4895-b48c-7b0b3e3730cb.png)

Thank you and best regards

**Comment by kaisp84** [comment]
I successfully compiled the extension with assemblies copied from Integration Services and Analysis Services extension folders on my machine and made "Deploy Mdx Script" work again. I simply changed the source path in [DLLs/SQL2019/copy-ssdt-dlls.bat](https://github.com/BIDeveloperExtensions/bideveloperextensions/pull/138/commits/384c96910f29e630d361d83eec54995075b7e5de#diff-8d38cb53878d3eb160ed1da02268e9a92fbe4d976c19999c346d7870b6ac0902) script to use assemblies from updated extensions. I didn't tested other functionalities and made some config changes which might not be needed. Also you should ignore the dlls from the pull request and use your own copy if you want to try it yourself

**Comment by furmangg** [comment]
We've published an [updated release](https://github.com/BIDeveloperExtensions/bideveloperextensions/releases/tag/v2.4.1) of BI Developer Extensions for Visual Studio 2019 that resolves this issue. Please note the compatible SSAS extension version. 

@kaisp84 thanks for your work on updating it and the pull request. This release fixes a few additional issues other than updating to the latest version of DLLs.
