### ISSUE TITLE
Printer Friendly Dimension usage on the latest version of SSAS cause an "object reference" error

### ISSUE THREAD

**Issue by setzor** [BIDeveloperExtensions/bideveloperextensions#139]
**Describe the bug**
In Visual Studio 2019 right clicking on a cube (within an OLAP multidimensional cube project) and selecting the option to generate the printer friendly dimension usage excel file causes an "object reference not set to an instance of an object" error. 

**Version**
![image](https://user-images.githubusercontent.com/9101477/218533475-e4dd05e5-ff45-42cb-b73d-9565092f98ce.png)

**To Reproduce**
1. Go to an existing OLAP multidimensional cube project
2. Click on a *.cube file in the Visual Studio solution explorer
3. Select the option named "Printer Friendly Dimension Usage..."

**Expected behavior**
An excel file to be generated showing the enterprise bus matrix of the cube/warehouse that can be printed (i.e. printer friendly)

**Screenshots**
The exact error: 
![image](https://user-images.githubusercontent.com/9101477/218533982-1fc492de-c6b7-4dc0-a0ca-83c9e5ce7b62.png)

**Additional context**
I've tested this with multiple OLAP cubes and get the same results. These are cubes/projects that I have in the past been able to generate these 'dimension usage' excel files for (used to work).

**Comment by furmangg** [comment]
We've published an [updated release](https://github.com/BIDeveloperExtensions/bideveloperextensions/releases/tag/v2.4.1) of BI Developer Extensions for Visual Studio 2019 that resolves this issue. Please note the compatible SSAS extension version.
