### ISSUE TITLE
SSIS/BIML: Script Transformation writing to a Blob Column

### ISSUE THREAD

**Issue by DA-BW** [BIDeveloperExtensions/bideveloperextensions#14]
Cannot write data to a BlobColumn from a ScriptComponentProject when generating a package using BIML.

Row.ColumName1.AddBlobData(enc.GetBytes(mystr.ToString()));

Results in error: "'string' does not contain a definition for 'GetBlobData' and no extension method 'GetBlobData' accepting a first argument of type 'string' could be found"

**Comment by furmangg** [comment]
We would recommend installing BimlExpress and retrying there:
https://varigence.com/BimlExpress

If it is still broken then raise this with Varigence support. They aren't supporting Biml in BI Developer Extensions anymore. 

It is in our todo list to make this clearer in our documentation.
