### ISSUE TITLE
Version 2.4.1 and Microsoft Visual Studio Community 2019 Version 16.10.0

### ISSUE THREAD

**Issue by petjoe** [BIDeveloperExtensions/bideveloperextensions#142]
After updating to version 2.4.1, the BIDS Helper no longer works with Microsoft Visual Studio Community 2019
Version 16.10.0. There is no error message. Right-clicking on an SSIS package does not show the deploy command.

**Comment by furmangg** [comment]
Please screenshot the Tools…Options…BIDS Helper… Version screen and post here. 

Will you be able to upgrade SSIS/SSRS/SSAS extension versions or would you prefer to downgrade BI Developer Extensions?

**Comment by petjoe** [comment]
![BIDS_Version](https://user-images.githubusercontent.com/31890280/226365547-f19eab96-76f7-494d-b08d-b996fb9b00cc.png)

Unfortunately, an upgrade is not possible, otherwise BIML Express will no longer work. 
So the only solution is to downgrade BIDS Helper to version 2.4.0.

**Comment by furmangg** [comment]
I would follow the instructions [here](https://github.com/BIDeveloperExtensions/bideveloperextensions/issues/141#issuecomment-1472050377) to downgrade to BI Developer Extensions 2.4.0. It should be compatible with your version of the SSIS extension.

I'm not sure the 2.4.0 will be compatible with the SSAS and SSRS versions you have installed, though. So if any of those features do not work, then unless you have an old link or copy of the old SSAS or SSRS extension installer, you may not have many options other than updating everything to the latest. See the [downloads](https://bideveloperextensions.github.io/downloads/) page for compatible versions.

I'm going to close this issue, but if you have further issues, please don't hesitate to keep me posted.
