### ISSUE TITLE
Unable to save Tabular Display Folders

### ISSUE THREAD

**Issue by nagadaveni** [BIDeveloperExtensions/bideveloperextensions#17]
When I try adding a folder and then save, I am getting a weird error like below.

Method not Found: System.Collections.Generic.IEnumerable`1<System.String>Microsoft.AnalysisServices.BackEnd/SandboxTransaction.Commit() at BIDSHelper.SSAS.TabularDisplayFolderPlugin

Also, I am getting the same error when I try creating a new action. Is this some kind of a known issue?

**Comment by furmangg** [comment]
There was a .Commit() method that used to return a list of strings. But somewhere along the way Microsoft changed it to be a void method. That broke our compiled code. I’ve worked around this so it works with old and new versions of this DLL. I'm working with a beta tester to validate my fix then will begin the process of pushing out another release.

https://github.com/BIDeveloperExtensions/bideveloperextensions/commit/1521dcee784d690ece79af2830288504762cfdb5

If you have an urgent need to test a beta build, let me know.

**Comment by furmangg** [comment]
This is fixed in release 2.1.1. Go to Tools... Extensions and Updates and then manually update. Or it should auto-update eventually.

Thanks for reporting.
