### ISSUE TITLE
BIML Features Not Available

### ISSUE THREAD

**Issue by DocGitHub** [BIDeveloperExtensions/bideveloperextensions#19]
Is there an update on 'BIML Features Not Available' ?

**Comment by furmangg** [comment]
Varigence has stopped providing Biml to BI Developer Extensions. Use their first party BimlExpress instead:
https://www.varigence.com/BimlExpress

**Comment by jdbuss** [comment]
So, just wanting to confirm, ALL BIML features will no longer be provided/supported through BIDS Helper then?

**Comment by furmangg** [comment]
@jdbuss that's correct. 

If you're using VS2013 or earlier you could download an old release 1.7.0 of BIDS Helper from https://github.com/BIDeveloperExtensions/bideveloperextensions/releases which I think contains Biml features but we have no plans of releasing bug fixes for that. The recommended approach is to install https://www.varigence.com/BimlExpress

**Comment by DocGitHub** [comment]
That sucks, cause informational messages in bidshelper are blocking error in BimlExpress....

column name must be unique despite each having their own outputbuffer....

**Comment by furmangg** [comment]
Can you elaborate on this? What versions of VS and what extension versions?
