### ISSUE TITLE
SSRS project error when running used or unused report datasets command

### ISSUE THREAD

**Issue by DaveProd** [BIDeveloperExtensions/bideveloperextensions#24]
Attached error occurs on 1st RDL of any SSRS project when running used or unused report datasets command

**Visual studio environment**

Microsoft Visual Studio Community 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.7.02558

Installed Version: Community

Microsoft Visual Studio Tools for Applications 2015   00322-20000-00000-AA266
Microsoft Visual Studio Tools for Applications 2015

Visual Basic 2015   00322-20000-00000-AA266
Microsoft Visual Basic 2015

Visual C# 2015   00322-20000-00000-AA266
Microsoft Visual C# 2015

Visual C++ 2015   00322-20000-00000-AA266
Microsoft Visual C++ 2015

Application Insights Tools for Visual Studio Package   7.0.20622.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015.1 (Beta8)   14.1.11107.0
ASP.NET and Web Tools 2015.1 (Beta8)

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
For additional information, visit http://www.asp.net/

BI Developer Extensions for Visual Studio 2015   2.1.1
BI Developer Extensions v2.1.1 for Visual Studio 2015 - An add-in to extend SQL Server Data Tools

Common Azure Tools   1.8
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

NuGet Package Manager   3.4.4
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Analysis Services   14.0.1012.227
Microsoft SQL Server Analysis Services Designer 
Version 14.0.1012.227

SQL Server Data Tools   14.0.61709.290
Microsoft SQL Server Data Tools

SQL Server Integration Services   
Microsoft SQL Server Integration Services Designer
Version 14.0.800.90

SQL Server Reporting Services   14.0.1012.227
Microsoft SQL Server Reporting Services Designers 
Version 14.0.1012.227

TypeScript   1.8.36.0
TypeScript tools for Visual Studio

**Comment by dgosbell** [comment]
I think you forgot to attach the error :) All I can see is the version information

**Comment by DaveProd** [comment]
Sorry about that. Here it is. Please let me know if you want it attached to
the Github issue.

Dave

**Comment by dgosbell** [comment]
I still can't see anything, if replied via email and attached something it has been stripped out.

**Comment by DaveProd** [comment]
Darren - Let's try a word doc with the image in it.

Thanks for your help.
Dave

**Comment by DaveProd** [comment]
I'm going to close issue and re-open with screenshot since the email is removing the attachments
