### ISSUE TITLE
SSRS project error when running used or unused report datasets command. 

### ISSUE THREAD

**Issue by DaveProd** [BIDeveloperExtensions/bideveloperextensions#25]
![bids helper](https://user-images.githubusercontent.com/36046612/35745492-b0f22626-0800-11e8-9356-33d67899e3b3.PNG)

See #24 for further info on VS environment

**Comment by DaveProd** [comment]
Any updates of this error?

**Comment by davepend** [comment]
This error is still out there: VS 2017 15.9.2, SSDT 15.1.61810.11040, BIDS 2.2.0.0

BIDS indicates SSDTBI 2019 (15.0.1000.59) for Visual Studio 2017.

![image](https://user-images.githubusercontent.com/45235630/48849346-c78d2600-ed6b-11e8-9abe-8d6f53875603.png)

**Comment by furmangg** [comment]
I'm happy to announce we just fixed this error with the newly released BI Developer Extensions v2.3.0 which is compatible with the latest SSDT for Visual Studio 2017. In Visual Studio 2017 under the Tools... Extensions and Updates menu and the Update tab you should see v2.3.0 show up. It should auto-update or you can manually update it.

Ensure you have the latest version of [SSDT installed](https://docs.microsoft.com/en-us/sql/ssdt/download-sql-server-data-tools-ssdt?view=sql-server-2017) (version 15.9.0 or higher) for Visual Studio 2017. Then in Visual Studio 2017 go to Tools... Extensions and Updates... Updates tab... then ensure you install any updates to Microsoft Analysis Services Projects, Microsoft Reporting Services Projects, or Microsoft Integration Services Projects. This release is designed to work with version 2.8.11 SSAS extension or higher, version 2.5.6 SSRS extension or higher, and 2.1 SSIS extension or higher.
