### ISSUE TITLE
Tabular Actions Editor not showing in VS2017 v2.1.1

### ISSUE THREAD

**Issue by computermike** [BIDeveloperExtensions/bideveloperextensions#26]
I just installed BI Dev Ext for VS2017, right clicked the .BIM file but Tabular actions Editor is not showing.

Is this a bug?  Is there another way to access the Actions editor?

Need to modify drillthrough query, please help.

Mike

**Comment by computermike** [comment]
I guess this is an issue with compatability level 1200 and above.  Nice how they don't mention that any where.

**Comment by computermike** [comment]
Didn't mean to close comment, would love to hear about when this might be fixed.

**Comment by dgosbell** [comment]
Is your model in the 1200 compatability mode or above? As noted at the top of the documentation for this feature [here](https://bideveloperextensions.github.io/features/TabularActionsEditor/) this is only available for models in the 1103 compatibility mode. It's not something we can "fix" it's a limitation of the new project file format. Until Microsoft extends this to support actions there is no place for us to inject them

**Comment by dgosbell** [comment]
Note that if you are on SSAS 2017 there is a new feature called DetailRowExpressions which you can define per table or per measure which lets you effectively write a custom Drillthrough query in DAX

**Comment by computermike** [comment]
I beleive DetailRowExtensions only works for compatability 1400, at least that is what I saw in one Microsoft doc.  I am at compatability level 1200.  Is there a solution for compatability level 1200?

**Comment by computermike** [comment]
I beleive DetailRowExtensions only works for compatability 1400, at least that is what I saw in one Microsoft doc.  I am at compatability level 1200.  Is there a solution for compatability level 1200?  Or is my info bad?   Hopefully I can do this somehow...



________________________________

**Comment by dgosbell** [comment]
No, I think you are right and there is no solution for the 1200 level. If you need to control drillthrough you either need to be on 1103 (and use BI Developer Extensions) or 1400 (and use Detail Row Expressions).

**Comment by computermike** [comment]
thanks for your help and responding Darren

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
