### ISSUE TITLE
BIML Features Not Available

### ISSUE THREAD

**Issue by chr0m** [BIDeveloperExtensions/bideveloperextensions#28]
"BIML Features are currently unavailable while we wait for Varigence to provide an update to the BimlEngine component."

Any ETA on when this will be available?

I wanted to use VS 2017 and BIML Express doesn't support it either.

**Comment by dgosbell** [comment]
No, sorry. Varigence are not responding to our emails so we have no ETA and don't even know if they will support this feature in future.
