### ISSUE TITLE
Issue During Installation

### ISSUE THREAD

**Issue by JamesCush** [BIDeveloperExtensions/bideveloperextensions#29]
Hi there! I am trying to install the SQL BI Developer Extensions in VS 2017, (Downloaded from the 'Extensions & Updates', and I am getting an error stating that prerequisites are required. It doesn't provide any further information. Any idea what that I may need? Thanks!
![issue](https://user-images.githubusercontent.com/11011814/37361407-332a11f8-26c9-11e8-98de-2afc2b7d4693.JPG)

**Comment by furmangg** [comment]
I'm your VS2017 can you go to Help... About Microsoft Visual Studio and copy that info into this thread? I haven't seen that error before.

**Comment by furmangg** [comment]
Sorry... "in your VS2017..."

**Comment by JamesCush** [comment]
Sure thing! - Here's the info copy/pasted and an image at the bottom
Thanks again!
--Jim

Microsoft Visual Studio Enterprise 2017 
Version 15.2 (26430.6) Release
VisualStudio.15.Release/15.2.0+26430.6
Microsoft .NET Framework
Version 4.7.02556

Installed Version: Enterprise

Architecture Diagrams and Analysis Tools   00369-60000-00001-AA628
Microsoft Architecture Diagrams and Analysis Tools

Visual Basic 2017   00369-60000-00001-AA628
Microsoft Visual Basic 2017

Visual C# 2017   00369-60000-00001-AA628
Microsoft Visual C# 2017

Visual F# 4.1   00369-60000-00001-AA628
Microsoft Visual F# 4.1

Application Insights Tools for Visual Studio Package   8.6.00404.2
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.30503.0
ASP.NET and Web Tools 2017

ASP.NET Web Frameworks and Tools 2017   5.2.50303.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.30209.0
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.2.5000.0
Microsoft Azure Data Lake Tools for Visual Studio

Common Azure Tools   1.9
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   3.0.17114.1
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

JavaScript Language Service   2.0
JavaScript Language Service

Microsoft Azure Hive Query Language Service   2.2.5000.0
Language service for Hive query

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.50131.1

NuGet Package Manager   4.2.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Project   1.0
Information about my package

Python   3.0.17114.1
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Python - Django support   3.0.17114.1
Provides templates and integration for the Django web framework.

Python - IronPython support   3.0.17114.1
Provides templates and integration for IronPython-based projects.

Python - Profiling support   3.0.17114.1
Profiling support for Python projects.

R Tools for Visual Studio   1.1.30413.0947
Provides project system, R Interactive window, plotting, and more for the R programming language.

Redgate ReadyRoll   1.16.18059.8649
Extend DevOps processes to your SQL Server databases and safely automate database deployments.

Visit https://www.red-gate.com/readyroll for more information.

Copyright (C) 2011 Red Gate Software Ltd. All rights reserved.

This software contains components from Component Owl.
SQL Server is a registered trademark of Microsoft Corporation.
Visual Studio is a registered trademark of Microsoft Corporation.

ReadyRoll contains code from the following open source software:

NuGet https://www.nuget.org/
SQL LocalDB Wrapper https://github.com/martincostello/sqllocaldb
Autofac https://autofac.org/
Json.NET https://json.net/
MahApps.Metro http://mahapps.com/
SemVer https://github.com/maxhauser/semver
Log4Net http://logging.apache.org/log4net/
StringTemplate https://github.com/antlr/stringtemplate4
Extended WPF Toolkit https://wpftoolkit.codeplex.com/
Code InfoBox VSX http://www.codeproject.com/Articles/55196/Code-InfoBox-Visual-Studio-Extension-VSX
OctoPack https://github.com/OctopusDeploy/OctoPack
SQLite https://sqlite.org/

This product contains icons from http://www.visualpharm.com distributed under a free backlink license.

For license details or other notices relating to the above software, please see NOTICE.TXT and EULA.rtf in the ReadyRoll application folder.
    

Redgate SQL Prompt   9.1.2.4363
Write, format, and refactor SQL effortlessly

SQL Server Analysis Services   14.0.806.134
Microsoft SQL Server Analysis Services Designer 
Version 14.0.806.134

SQL Server Data Tools   15.1.61702.140
Microsoft SQL Server Data Tools

SQL Server Reporting Services   14.0.806.134
Microsoft SQL Server Reporting Services Designers 
Version 14.0.806.134

SsmsVsIntegration   1.0
Information about my package

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript   2.2.2.0
TypeScript tools for Visual Studio


![image](https://user-images.githubusercontent.com/11011814/37414641-03c047b8-2780-11e8-88ae-713d34c4259a.png)

**Comment by JamesCush** [comment]
I updated VS to the latest version and then I was able to get it install A-OK!
