### ISSUE TITLE
GitHub support for Smart Diff

### ISSUE THREAD

**Issue by furmangg** [BIDeveloperExtensions/bideveloperextensions#3]
Add support for looking a commit history in GitHub and choosing a commit for comparison.

**Comment by karisgood** [comment]
I second this

**Comment by furmangg** [comment]
I know everyone who has voted for this feature will be pleased to know that or the 2.3.2 release for Visual Studio 2017 and Visual Studio 2019 GitHub is now supported in Smart Diff. Please test out this support and post back here if you have any problems in your particular environment.

Release 2.3.2 is available in the [Visual Studio Marketplace](https://bideveloperextensions.github.io/downloads/) and your install should auto-update.
