### ISSUE TITLE
Error after install from Gallery "bids helper biml features are currently unavailable"

### ISSUE THREAD

**Issue by ziyunxiao** [BIDeveloperExtensions/bideveloperextensions#30]
Error message: 

bids helper biml features are currently unavailable while we wait for Varigence to provide an update to the BimlEngine component

![image](https://user-images.githubusercontent.com/6117913/37869068-b17a2038-2f76-11e8-9736-8c575a9d7544.png)

**Comment by dgosbell** [comment]
This is not really an error, just a statement of fact. The BIML features in BI Developer Extensions were kindly provided by Varigence in the past, but they have not provided us with an update of the engine which works with the latest versions of Visual Studio. Unfortunately they have also stopped responding to our attempts to communicate with them so we don't really know what is going one. So until further notice there is nothing we can do.

In the mean time they have released their own BIML Express add-in which you could try.
