### ISSUE TITLE
SSAS 2017/Visual Studio 2017: Not seeing Actions on the context menu?

### ISSUE THREAD

**Issue by seedjay1** [BIDeveloperExtensions/bideveloperextensions#33]
Hi,

Am I doing something wrong or is the Actions feature not available?

Thanks,
cdj

![image](https://user-images.githubusercontent.com/31414209/39830921-a7e37b62-5377-11e8-90d7-5b201cfb6075.png)

**Comment by dgosbell** [comment]
What compatibility mode are you running in? We can only inject actions into 1103 models as they use XMLA for their schema definition which has support for action elements. For 1200 or later Microsoft has not provided anywhere in the new json based schemas for actions to be included, so we need to wait until Microsoft adds support for these.

**Comment by seedjay1** [comment]
Oooh. That's too bad. :(

Thanks for the reply!
