### ISSUE TITLE
Update to BimlEngine component error

### ISSUE THREAD

**Issue by AmirHossein87** [BIDeveloperExtensions/bideveloperextensions#36]
hi
when i download and install "BI Developer Extension" , i see the "Add new icon Biml" but error occur  with below image

![untitled](https://user-images.githubusercontent.com/22929994/41394691-2cb9db74-6fc0-11e8-9e38-31b434b79cf5.png)

**Comment by dgosbell** [comment]
This is not so much an error as a statement of fact. The BIML functionality in earlier versions of BI Developer Extensions was kindly provided by Varigence. However they have not provided us with an updated version of the BIML components that will work in a Visual Studio 2015/2017 shell and are not responding to any of our emails. 

They have been working on their own extension called BIML Express, so you could try seeing if that works for you. But at the moment our hands are tied.

**Comment by AmirHossein87** [comment]
thanks dear
i install BimlExpress but now not show BimlExpress  in menu and not exists in "Extensions and update" list
