### ISSUE TITLE
Shown as installed but not working

### ISSUE THREAD

**Issue by Mandalapu320** [BIDeveloperExtensions/bideveloperextensions#41]
I installed the BI developer extension on my VS 2017 installation. It shows as installed
![image](https://user-images.githubusercontent.com/32055247/45330077-fab27c80-b5a6-11e8-9437-d2a9b747539c.png)
...but I'm not able to add BIML file in an SSIS project, I get this error:
![image](https://user-images.githubusercontent.com/32055247/45330113-2c2b4800-b5a7-11e8-8728-10a374c482b5.png)
When I tried to install by executing the visx installer, I get an error. Here's the error and error log.
![image](https://user-images.githubusercontent.com/32055247/45330231-c8554f00-b5a7-11e8-9219-a05b09644564.png)

System specs:

- Win 10 x64 Enterprise
- Visual studio 2017 Professional and Enterprise instances
- SQL Server 2017 Enterprise
- SSDT 2017
- Lots of space in C drive and lots of RAM left.

If this is not an issue, how can I resolve it?

**Comment by Mandalapu320** [comment]
I have also tried to install BIML Express. Even that isn't installing. I'm in a conversation with Varigence for that.

**Comment by dgosbell** [comment]
This is not an error, but there is nothing we can do about. We are still waiting on Varigence to add support for VS 2017, but to be honest we’ve given up waiting. They are not responding to our attempts to contact them. 

Sorry, but your only options are to either use BIDS Helper with an older copy of VS or to try and get BIML Express working
