### ISSUE TITLE
Expression and Configuration Highlighter SSDT 15.8.2

### ISSUE THREAD

**Issue by septplla** [BIDeveloperExtensions/bideveloperextensions#46]
I just upgraded from SSDT 15.7.1 to 15.8.2 (using VS 2017), and the "Expression and Configuration Highlighter" isn't visible on the connection managers(that are using package configurations) in SSIS anymore. I am developing for SQL 2016.

**Comment by MaxBarj** [comment]
Hey,

You should refer to the last post in issue #43 
Developpers are aware of the problem and working on an update.

**Comment by septplla** [comment]
Hi, thanks for your quick reply, I tried to read through the other issues, but I missed that, sorry! :-)
I'll close this one then...

BTW, thanks for a great product, we all use it in our BI-team! :-)
