### ISSUE TITLE
Smart Diff not working in v2.2.0.0 (Smart Diff requires SSAS extension in SSDT to be installed)

### ISSUE THREAD

**Issue by mpalandri** [BIDeveloperExtensions/bideveloperextensions#50]
Hi, just installed v 2.2.0.0 and tried Smart Diff.  

When attempting to use SmartDiff, I get:
Could not load file or assembly 'Microsoft.AnalysisServices.Backedn, Version 15.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies.  The system cannot find the file specified.

This happens if I use the Default VS DIff View, or a third party command line viewer, vsdiff.exe.

I get this message in VS Options | BIDS Helper | Version:

BIDS Helper encountered an error when Visual Studio started:
BIDS Helper encountered an error when Visual Studio started:
Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at BIDSHelper.BIDSHelperPackage.Initialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions\BidsHelperPackage.cs:line 120
Could not load file or assembly 'Microsoft.AnalysisServices.Common.FrontEnd, Version=15.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.
Fusion Log:
WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

Could not load file or assembly 'Microsoft.AnalysisServices.Common.FrontEnd, Version=15.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.
Fusion Log:
WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

Could not load file or assembly 'Microsoft.AnalysisServices.Common.FrontEnd, Version=15.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.
Fusion Log:
WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

BIDS Helper encountered an error when Visual Studio started:
BIDS Helper plugin constructor failed on TabularHideMemberIfPlugin: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.Initialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions\BidsHelperPackage.cs:line 154

Inner exception:
Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.Initialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions\BidsHelperPackage.cs:line 154
Inner exception:
Could not load file or assembly 'Microsoft.AnalysisServices.Common.FrontEnd, Version=15.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.
   at BIDSHelper.TabularHideMemberIfPlugin..ctor(BIDSHelperPackage package)BIDS Helper encountered an error when Visual Studio started:
BIDS Helper plugin constructor failed on TabularSyncDescriptionsPlugin: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.Initialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions\BidsHelperPackage.cs:line 154

Inner exception:
Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.Initialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions\BidsHelperPackage.cs:line 154
Inner exception:
Could not load file or assembly 'Microsoft.AnalysisServices.Common.FrontEnd, Version=15.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.
   at BIDSHelper.SSAS.TabularSyncDescriptionsPlugin..ctor(BIDSHelperPackage package)

**Comment by furmangg** [comment]
What do you see at the top of that BIDS Helper Version screen?

You are in a SSAS Tabular project correct? What compatibility level is it?

Did you not get a pop up saying that you have SSDT for SQL 2017 installed and BI Developer Extensions needs to reconfigure itself? If you close and reopen all Visual Studio instances can you reproduce the problem? It should have closed Visual Studio for you and reopened it with the right configuration.

**Comment by mpalandri** [comment]
The top of the version screen says: 

BI Developer Extensions for SQL Server 2019 
Version 2.2.0.0 
https://bideveloperextensions.github.io 
SSDTBI 2019 (15.0.900.163) for Visual Studio 2017 

The project I'm working on is a Business Intelligence Integration Services project, just a run of the mill project to create SSIS packages. Target is SQL Server 2016, I'm not sure how to determine the compatibility level. I would really like to use Smart Diff on SSRS rdl files as well, I get the same error when I try that. 

To install, I selected the new version from the VS Tools | Extensions and Updates menu, then closed VS, and installation began. When it completed, there was a pop up message, but I don't recall if it said anything about BI Developer Extensions reconfiguring itself. 

I have opened and closed VS several time since then, but the error remains. 

Here is the info from the VS Help | About dialog: 

Microsoft Visual Studio Professional 2017 
Version 15.8.5 
VisualStudio.15.Release/15.8.5+28010.2036 
Microsoft .NET Framework 
Version 4.7.02556 

Installed Version: Professional 

Microsoft Visual Studio Tools for Applications 2017 00369-60000-00001-AA979 
Microsoft Visual Studio Tools for Applications 2017 

Visual C++ 2017 00369-60000-00001-AA979 
Microsoft Visual C++ 2017 

BI Developer Extensions 2017 Extension 2.2.0 
BI Developer Extensions 2017 Visual Studio Extension v2.2.0 - An add-in to extend SQL Server Data Tools 

C# Tools 2.9.0-beta8-63208-01 
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used. 

Common Azure Tools 1.10 
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools. 

JavaScript Language Service 2.0 
JavaScript Language Service 

Microsoft JVM Debugger 1.0 
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines 

Microsoft MI-Based Debugger 1.0 
Provides support for connecting Visual Studio to MI compatible debuggers 

Microsoft Visual C++ Wizards 1.0 
Microsoft Visual C++ Wizards 

Microsoft Visual Studio VC Package 1.0 
Microsoft Visual Studio VC Package 

NuGet Package Manager 4.6.0 
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/. 

PowerShell Pro Tools for Visual Studio 1.0 
A set of tools for developing and debugging PowerShell scripts and modules in Visual Studio. 

ProjectServicesPackage Extension 1.0 
ProjectServicesPackage Visual Studio Extension Detailed Info 

ResourcePackage Extension 1.0 
ResourcePackage Visual Studio Extension Detailed Info 

ResourcePackage Extension 1.0 
ResourcePackage Visual Studio Extension Detailed Info 

ResXManager 1.29.1315.0 
Manage localization of all ResX-Based resources in one place. Shows all resources of a solution and let's you edit the strings and their localizations in a well-arranged data grid. 

SQL Server Data Tools 15.1.61808.07020 
Microsoft SQL Server Data Tools 

SQL Server Integration Services 
Microsoft SQL Server Integration Services Designer 
Version 15.0.900.30 

SQL Server Reporting Services 15.0.900.163 
Microsoft SQL Server Reporting Services Designers 
Version 15.0.900.163 

Visual Basic Tools 2.9.0-beta8-63208-01 
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used. 

Visual Studio Code Debug Adapter Host Package 1.0 
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio 

Mike 
.

**Comment by mpalandri** [comment]
Thank you. 

I installed SSAS, and Smart Diff works properly now. 

Mike 
.

**Comment by furmangg** [comment]
We have released a beta release which fixes the issue identified in this thread. To do Smart Diff on an SSIS package you shouldn't have to have the SSAS extension installed. And vice versa you don't have to have the SSIS extension installed to use Smart Diff on an SSAS project. 

We plan to allow the week of 2019-04-22 for beta testing before releasing this to the public. Please download the release from here and please read the release notes there:
https://github.com/BIDeveloperExtensions/bideveloperextensions/releases/tag/v2.3.0_beta

**Comment by mpalandri** [comment]
Hi, 

Thank you for notifying me of the update to BIDS Helper 


I downloaded and installed the new BIDS Helper beta last week after updating SSDT as instructed. 

Up til now I have had no problems, though I didn't actually use any extensions. Today I used the Create Fixed Width Columns feature, I don't know if that is related. 

Now, when I try to open the Variables page of a package, BIDS Helper crashes. This is in the application event log: 




First error: 

Application: devenv.exe 
Framework Version: v4.0.30319 
Description: The process was terminated due to an unhandled exception. 
Exception Info: System.IO.FileNotFoundException 
at BIDSHelper.SSIS.VariablesWindowPlugin.RefreshHighlights() 
at BIDSHelper.SSIS.VariablesWindowPlugin.grid_Invalidated(System.Object, System.Windows.Forms.InvalidateEventArgs) 
at System.Windows.Forms.Control.OnInvalidated(System.Windows.Forms.InvalidateEventArgs) 
at System.Windows.Forms.Control.NotifyInvalidate(System.Drawing.Rectangle) 
at System.Windows.Forms.Control.Invalidate(Boolean) 
at System.Windows.Forms.Control.Refresh() 
at Microsoft.SqlServer.Management.UI.Grid.GridControl.UpdateGridInternal(Boolean) 
at Microsoft.DataTransformationServices.Design.VariablesToolWindow+BaseDlgGridControl.UpdateGridInternal(Boolean) 
at Microsoft.SqlServer.Management.UI.Grid.GridControl.UpdateGrid(Boolean) 
at Microsoft.SqlServer.Management.UI.Grid.DlgGridControl.EndInit() 
at Microsoft.DataTransformationServices.Design.GridColumnWidthManager.ResizeColumns() 
at Microsoft.DataTransformationServices.Design.GridColumnWidthManager.gridControl_Resize(System.Object, System.EventArgs) 
at System.Windows.Forms.Control.OnResize(System.EventArgs) 
at System.Windows.Forms.Control.OnSizeChanged(System.EventArgs) 
at Microsoft.SqlServer.Management.UI.Grid.GridControl.OnSizeChanged(System.EventArgs) 
at System.Windows.Forms.Control.UpdateBounds(Int32, Int32, Int32, Int32, Int32, Int32) 
at System.Windows.Forms.Control.UpdateBounds() 
at System.Windows.Forms.Control.WmWindowPosChanged(System.Windows.Forms.Message ByRef) 
at System.Windows.Forms.Control.WndProc(System.Windows.Forms.Message ByRef) 
at Microsoft.SqlServer.Management.UI.Grid.GridControl.WndProc(System.Windows.Forms.Message ByRef) 
at System.Windows.Forms.Control+ControlNativeWindow.OnMessage(System.Windows.Forms.Message ByRef) 
at System.Windows.Forms.Control+ControlNativeWindow.WndProc(System.Windows.Forms.Message ByRef) 
at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr, Int32, IntPtr, IntPtr) 



Second error: 

Faulting application name: devenv.exe, version: 15.9.28307.423, time stamp: 0x5c5b5342 
Faulting module name: KERNELBASE.dll, version: 10.0.17763.348, time stamp: 0x53015794 
Exception code: 0xe0434352 
Fault offset: 0x0011c632 
Faulting process id: 0x3204 
Faulting application start time: 0x01d4feb467f49a40 
Faulting application path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\devenv.exe 
Faulting module path: C:\Windows\System32\KERNELBASE.dll 
Report Id: 3ec549f9-25a6-4a77-b321-d8b7548a8aea 
Faulting package full name: 
Faulting package-relative application ID: 



I uninstalled the beta and reinstalled from within VS Extensions and Updates, which did not help. The error did not occur while BID Helper was uninstalled, but returned after it was reinstalled. 

This version information was shown: 

BIDS Helper Version shows v 2.3.1.0 
SSDTBI 2019 (15.0.1200.68) for Visual Studio 2017 was detected. 
SSDT Extensions Installed: SSAS (N/A), SSIS (2.2), SSRS (2.0) 
Please upgrade SSRS to 2.5.6 

I could not find SSRS 2.5.6, only 2.5.5 and 2.5.7. I installed 2.5.7 


The version information is now: 
BIDS Helper Version shows v 2.3.1.0 
SSDTBI 2019 (15.0.1200.68) for Visual Studio 2017 was detected. 
SSDT Extensions Installed: SSAS (N/A), SSIS (2.2), SSRS (2.5.7) 



Now when I attempt to do a variety of things in VS, I get a BIDS Helper exception dialog. I'm going to paste in a graphic: 


This appears every repeatedly when I click various things in VS, e.g., Open project in Solution explorer, open a package in a project, switch between the VS Variables, Error List, and Output windows, and others. 


To summarize, before updating SSRS from 2.0 to 2.5.7, VS would crash when attempting to open the SSIS variables window, after updating to SSRS 2.5.7, the error message about is displayed many times. 


I Using VS2017, here's the Help | About: 

Microsoft Visual Studio Professional 2017 
Version 15.9.7 
VisualStudio.15.Release/15.9.7+28307.423 
Microsoft .NET Framework 
Version 4.7.03190 

Installed Version: Professional 

Microsoft Visual Studio Tools for Applications 2017 00369-60000-00001-AA386 
Microsoft Visual Studio Tools for Applications 2017 

BI Developer Extensions for Visual Studio 2017 2.3.1 
BI Developer Extensions v2.3.1 for Visual Studio 2017 - An add-in to extend SQL Server Data Tools 

C# Tools 2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a 
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used. 

Common Azure Tools 1.10 
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools. 

NuGet Package Manager 4.6.0 
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/. 

PowerShell Pro Tools for Visual Studio 1.0 
A set of tools for developing and debugging PowerShell scripts and modules in Visual Studio. 

ProjectServicesPackage Extension 1.0 
ProjectServicesPackage Visual Studio Extension Detailed Info 

ResourcePackage Extension 1.0 
ResourcePackage Visual Studio Extension Detailed Info 

ResourcePackage Extension 1.0 
ResourcePackage Visual Studio Extension Detailed Info 

SQL Server Data Tools 15.1.61901.24070 
Microsoft SQL Server Data Tools 

SQL Server Integration Services 
Microsoft SQL Server Integration Services Designer 
Version 15.0.1100.123 

SQL Server Reporting Services 15.0.1331.137 
Microsoft SQL Server Reporting Services Designers 
Version 15.0.1331.137 

Visual Basic Tools 2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a 
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used. 

Visual Studio Code Debug Adapter Host Package 1.0 
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio 





Thank you for your work on BIDS Helper. 



Mike 
.

**Comment by furmangg** [comment]
@mpalandri I copied your bug report to a new thread and posted a debug build:
https://github.com/BIDeveloperExtensions/bideveloperextensions/issues/63

Thanks for reporting this!
