### ISSUE TITLE
Deploy mdx script fails in Visual Studio 2017 (Version 15.8.9)

### ISSUE THREAD

**Issue by kaisp84** [BIDeveloperExtensions/bideveloperextensions#51]
When I try to deploy the MDX script of an SSAS project targeting SQLServer 2012 I receive the following error message:

Could not load file or assembly: 'Microsoft.AnalysisServices.AdomdClient, ....

The complete error message is shown on the attached screenshot.
![errormessage](https://user-images.githubusercontent.com/20833767/48832064-9a934000-ed78-11e8-9b1f-4aa5f64ae824.PNG)

SSAS / Analysis services project extension version: 2.2
Visual Studio version: 15.8.9
SSAS Project target version: SQL Server 2012

**Comment by furmangg** [comment]
Easiest way for you to fix this is to install:
http://download.microsoft.com/download/3/8/B/38B8BD8C-E6AB-4B9F-AB1E-03C59A477C48/x64_15.0.1000.81_SQL_AS_ADOMD.msi

I will leave this thread open as I suspect we can switch to the AppLocal version of the DLL as a more elegant fix.

**Comment by furmangg** [comment]
I've got a working build where this is fixed and am testing. Thanks for reporting it. Will keep this thread posted when it is released.

**Comment by furmangg** [comment]
I have just published release 2.2.1 for Visual Studio 2017 that fixes this issue. Thanks for reporting it.

Please go to Extensions and Updates and make sure you have 2.2.1 installed.

**Comment by kaisp84** [comment]
I updated to the new version and everythings works as expected agains. Thanks
