### ISSUE TITLE
Smart Diff Not Working in 2.2.1.0

### ISSUE THREAD

**Issue by Jan-weinmann** [BIDeveloperExtensions/bideveloperextensions#54]
When I try to use Smart Diff I get the following dialog:

![image](https://user-images.githubusercontent.com/39568418/50526773-f3f23b80-0aa9-11e9-8d4c-f62e354378dc.png)

I am using Visual Studio Enterprise 2017 (version 15.9.4), running on Windows 7 Enterprise SP-1.  Analysis Services is installed.

About Visual Studio:
-------------------------------------------------------------------------------
Microsoft Visual Studio Enterprise 2017 
Version 15.9.4
VisualStudio.15.Release/15.9.4+28307.222
Microsoft .NET Framework
Version 4.7.03062

Installed Version: Enterprise

Microsoft Visual Studio Tools for Applications 2017   00369-60000-00001-AA325
Microsoft Visual Studio Tools for Applications 2017

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASP.NET and Web Tools 2017   15.9.04012.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   15.8.31590
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.60913.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.9.03024.0
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.3.5001.7
Microsoft Azure Data Lake Tools for Visual Studio

Azure Stream Analytics Tools for Visual Studio   2.3.5001.7
Microsoft Azure Stream Analytics Tools for Visual Studio

BI Developer Extensions 2017 Extension   2.2.1
BI Developer Extensions 2017 Visual Studio Extension v2.2.1 - An add-in to extend SQL Server Data Tools

C# Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

Microsoft Azure HDInsight Azure Node   2.3.5001.7
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.3.5001.7
Language service for Hive query

Microsoft Azure Stream Analytics Language Service   2.3.5001.7
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.10730.2

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   1.0
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Project   1.0
Information about my package

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Redgate SQL Change Automation   3.0.18341.3167
Extend DevOps processes to your SQL Server databases and safely automate database deployments.

Visit https://www.red-gate.com/sca/productpage for more information.

Copyright (C) 2011 Red Gate Software Ltd. All rights reserved.

This software contains components from Component Owl.
SQL Server is a registered trademark of Microsoft Corporation.
Visual Studio is a registered trademark of Microsoft Corporation.

SQL Change Automation contains code from the following open source software:

NuGet https://www.nuget.org/
SQL LocalDB Wrapper https://github.com/martincostello/sqllocaldb
Autofac https://autofac.org/
Json.NET https://json.net/
MahApps.Metro http://mahapps.com/
SemVer https://github.com/maxhauser/semver
Log4Net http://logging.apache.org/log4net/
StringTemplate https://github.com/antlr/stringtemplate4
Extended WPF Toolkit https://wpftoolkit.codeplex.com/
Code InfoBox VSX http://www.codeproject.com/Articles/55196/Code-InfoBox-Visual-Studio-Extension-VSX
OctoPack https://github.com/OctopusDeploy/OctoPack
SQLite https://sqlite.org/

This product contains icons from http://www.visualpharm.com distributed under a free backlink license.

For license details or other notices relating to the above software, please see NOTICE.TXT and EULA.rtf in the SQL Change Automation application folder.
    

Redgate SQL Prompt   9.4.3.7121
Write, format, and refactor SQL effortlessly

Redgate SQL Search   3.1.9.2167
Search functionality for SQL Server databases, from within Visual Studio

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

SQL Server Analysis Services   14.0.1016.285
Microsoft SQL Server Analysis Services Designer 
Version 14.0.1016.285

SQL Server Data Tools   15.1.61810.11040
Microsoft SQL Server Data Tools

SQL Server Integration Services   
Microsoft SQL Server Integration Services Designer
Version 14.0.3002.113

SQL Server Reporting Services   14.0.1016.285
Microsoft SQL Server Reporting Services Designers 
Version 14.0.1016.285

SsmsVsIntegration   1.0
Information about my package

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TSVN   1.9
Control TortoiseSVN from within Visual Studio

TypeScript Tools   15.9.20918.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualSVN   6.2.2
Integration with Subversion version control. For more information about VisualSVN, see the VisualSVN website at https://www.visualsvn.com
Copyright © 2018 VisualSVN Software Ltd. All rights reserved.

**Comment by furmangg** [comment]
What do you see when you go to Tools... Options... BIDS Helper... Preferences? I assume it should show "Visual Studio Built-in" and you should have it set to use the default diff viewer. If yours looks different let me know.

![image](https://user-images.githubusercontent.com/9261846/50529557-5869c680-0abb-11e9-84ac-75fdd22bc5a5.png)

**Comment by furmangg** [comment]
It looks like your Visual Studio 2017 needs to be updated. Install the latest 2.3.0 release of BI Developer Extensions. Ensure you have the latest version of [SSDT installed](https://docs.microsoft.com/en-us/sql/ssdt/download-sql-server-data-tools-ssdt?view=sql-server-2017) (version 15.9.0 or higher) for Visual Studio 2017. Then in Visual Studio 2017 go to Tools... Extensions and Updates... Updates tab... then ensure you install any updates to Microsoft Analysis Services Projects, Microsoft Reporting Services Projects, or Microsoft Integration Services Projects. This release is designed to work with version 2.8.11 SSAS extension or higher, version 2.5.6 SSRS extension or higher, and 2.1 SSIS extension or higher.

I'm going to close this issue as it's a bit old and this feature is working for me with the above configuration. But please write back if the above doesn't fix it for you.
