### ISSUE TITLE
Assembly files missing or Could not Load - 'Microsoft.ReportViewer.WinForms.AppLocal'

### ISSUE THREAD

**Issue by williamchond** [BIDeveloperExtensions/bideveloperextensions#56]
Hi There,

I'm running SSDT on Visual Studio 2017.
I recently installed BIDeveloperExtensions for SQL Server 2019 (version 2.2.1.0) Not sure if it matters, because my SQL Server is 2017?

However the main issue is using all the features. I am not able to use any of the Tabular features, such as Printer Friendly Dimension Usage. The error message that comes up is below (Microsoft.ReportViewer.WinForms.AppLocal)
![2019-02-15_16-06-47](https://user-images.githubusercontent.com/20215250/52835712-bae65700-313b-11e9-8196-6afc75ca1a11.png)

ANother one is running Roles Report. I got error message ('Microsoft.AnalysisServices.BackEnd'). See below.
![2019-02-15_16-07-41](https://user-images.githubusercontent.com/20215250/52835747-e701d800-313b-11e9-936e-40aabe86006d.png)

Am I missing any important step during installation or in my Visual Studio? Please help.

Thank you.

**Comment by dgosbell** [comment]
We don't have a 2019 version yet so you probably have the VS 2017 version. When you installed SSDT did you add all the BI components? Can you go into Help - About Microsoft Visual Studio and click the Copy Info button and paste the results into this issue?

**Comment by williamchond** [comment]
Thanks for your response dgosbell.

This is the copy info,
Microsoft SQL Server Data Tools for Visual Studio 2017  (SSDT)
Version 15.9.7
VisualStudio.15.Release/15.9.7+28307.423
Microsoft .NET Framework
Version 4.6.01586

Installed Version: IDE Standard

Microsoft Visual Studio Tools for Applications 2017   00371-40000-00001-AA865
Microsoft Visual Studio Tools for Applications 2017

ApexSQL Refactor   1.0
ApexSQL Refactor Visual Studio Addin Component

ApexSQL Stub   1.0


BI Developer Extensions 2017 Extension   2.2.1
BI Developer Extensions 2017 Visual Studio Extension v2.2.1 - An add-in to extend SQL Server Data Tools

C# Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Project   1.0
Information about my package

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

SQL Server Analysis Services   15.0.1300.59
Microsoft SQL Server Analysis Services Designer 
Version 15.0.1300.59

SQL Server Data Tools   15.1.61901.24070
Microsoft SQL Server Data Tools

SQL Server Integration Services   
Microsoft SQL Server Integration Services Designer
Version 15.0.900.40

SQL Server Reporting Services   15.0.900.163
Microsoft SQL Server Reporting Services Designers 
Version 15.0.900.163

SsmsVsIntegration   1.0
Information about my package

Visual Basic Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

**Comment by furmangg** [comment]
See this other thread: https://github.com/BIDeveloperExtensions/bideveloperextensions/issues/55

I would recommend uninstalling that version of SSDT and rolling back to 15.8.2 or 15.9.0 SSDT versions. We will keep monitoring the situation but think this is the best approach given the known SSDT issues regarding Multidimensional models in the latest 15.9.7 version.

Darren, the BI Developer Extensions 2.2.1 release does support the 15.0 assemblies (SQL 2019). We don't have SQL 2019 new features handled but the existing features work with this version. It's just that the latest SSDT has some issues. (We were both on an email thread mentioning this earlier in the week.)

**Comment by williamchond** [comment]
Hi @furmangg 
I see. How do I rollback my current version to the 15.9.0 SSDT? Is there any guide I can follow on this?

**Comment by furmangg** [comment]
Did you ever figure this out. Roughly you should uninstall the newer version and download and install the older version of SSDT. If you want to write up more detailed instructions that would be helpful to the community.

**Comment by williamchond** [comment]
Hi furmangg,

I followed your instructions and seems to work.
I uninstall SSDT and download the version 15.9.0 and seems to work. My suggestion is to do offline install on the SSDT to avoid auto upgrade to the latest version (https://docs.microsoft.com/en-us/sql/ssdt/download-sql-server-data-tools-ssdt?view=sql-server-2017)
Download SQL Server Data Tools (SSDT) - docs.microsoft.com<https://docs.microsoft.com/en-us/sql/ssdt/download-sql-server-data-tools-ssdt?view=sql-server-2017>
Download and install SQL Server Data Tools (SSDT) for Visual Studio. 01/19/2019; 4 minutes to read Contributors. all; In this article. APPLIES TO: SQL Server Azure SQL Database Azure SQL Data Warehouse Parallel Data Warehouse SQL Server Data Tools is a modern development tool for building SQL Server relational databases, Azure SQL databases, Analysis Services (AS) data models, Integration ...
docs.microsoft.com



Kind regards,
William
________________________________

**Comment by furmangg** [comment]
I'm happy to announce we just released BI Developer Extensions v2.3.0 which is compatible with the latest SSDT for Visual Studio 2017. It was quite a challenging effort as the SSDT team has been updating SSAS and SSRS extensions independently and with a quite frequent pace. Previously shared DLLs are now SSAS or SSRS specific and DLL version numbers are iterating with each release. All BI Developer Extensions are currently working and we hope we have put code in place so that it will continue to work as SSDT DLL version numbers increment.

In Visual Studio 2017 under the Tools... Extensions and Updates menu and the Update tab you should see v2.3.0 show up. It should auto-update or you can manually update it.

Please create a new issue if you find that anything isn't working as expected.

Ensure you have the latest version of [SSDT installed](https://docs.microsoft.com/en-us/sql/ssdt/download-sql-server-data-tools-ssdt?view=sql-server-2017) (version 15.9.0 or higher) for Visual Studio 2017. Then in Visual Studio 2017 go to Tools... Extensions and Updates... Updates tab... then ensure you install any updates to Microsoft Analysis Services Projects, Microsoft Reporting Services Projects, or Microsoft Integration Services Projects. This release is designed to work with version 2.8.11 SSAS extension or higher, version 2.5.6 SSRS extension or higher, and 2.1 SSIS extension or higher.
