### ISSUE TITLE
Deploy SSIS Packages is missing

### ISSUE THREAD

**Issue by maddoc1** [BIDeveloperExtensions/bideveloperextensions#57]
There is no such option "Deploy (BIDS Helper)" in project properties.
Using package deployment model.
VS 15.7.4
SSDT 15.7.1

**Comment by mattcushing** [comment]
when I hit properties for my 2012 project, I'm seeing the Deployment option under Config Props, but I'm not seeing where it'll let me change the deployment type so I can deploy directly to MSDB instead of SSIS Catalog.

**Comment by dgosbell** [comment]
@maddoc1 - when you go to Help > About do you see BI Developer Extensions in the list? Can you double check in Tools > Options > BIDS Helper that the "Deploy SSIS Packages" feature is set to True?

@mattcushing - Your issue is not really related to the original one here. The option to deploy to MSDB is only available if you are in "package" deployment mode, so if you can't see it you are probably in "project" deployment mode. Changing the deployment mode is not a BI Developer Extensions feature as such, but you can do this by right clicking on your project and choosing the following: 
![image](https://user-images.githubusercontent.com/8241830/55038514-2e518180-5075-11e9-82aa-ad135784cdf9.png)

Note however that package deployment mode and saving packages in MSDB is the old backward compatible mode. I have not used this option since SQL 2012 came out, I've been using the new project deployment mode which stores packages in the SSIS Catalog exclusively since it was first made available in 2012

**Comment by maddoc1** [comment]
@mattcushing  Yes, here BI Helper is in the list:
![image](https://user-images.githubusercontent.com/7616746/55073579-b6944e80-5096-11e9-89ce-9aaabd998632.png)

"Deploy SSIS Packages" feature is set to True:
![image](https://user-images.githubusercontent.com/7616746/55073640-e5122980-5096-11e9-9415-21298641df84.png)

But also I see this error under the version setting:
![image](https://user-images.githubusercontent.com/7616746/55073666-fbb88080-5096-11e9-9db2-62d5f3fa4a89.png)

The error:
`BIDS Helper encountered an error when Visual Studio started:
BIDS Helper encountered an error when Visual Studio started:
Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at BIDSHelper.BIDSHelperPackage.Initialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions\BidsHelperPackage.cs:line 120
Could not load file or assembly 'Microsoft.AnalysisServices.Common.FrontEnd, Version=15.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.
Fusion Log:
WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].



Could not load file or assembly 'Microsoft.AnalysisServices.Common.FrontEnd, Version=15.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.
Fusion Log:
WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].



Could not load file or assembly 'Microsoft.AnalysisServices.Common.FrontEnd, Version=15.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.
Fusion Log:
WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].


BIDS Helper encountered an error when Visual Studio started:
BIDS Helper plugin constructor failed on TabularHideMemberIfPlugin: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.Initialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions\BidsHelperPackage.cs:line 154

Inner exception:
Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.Initialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions\BidsHelperPackage.cs:line 154
Inner exception:
Could not load file or assembly 'Microsoft.AnalysisServices.Common.FrontEnd, Version=15.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.
   at BIDSHelper.TabularHideMemberIfPlugin..ctor(BIDSHelperPackage package)BIDS Helper encountered an error when Visual Studio started:
BIDS Helper plugin constructor failed on TabularSyncDescriptionsPlugin: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.Initialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions\BidsHelperPackage.cs:line 154

Inner exception:
Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.Initialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions\BidsHelperPackage.cs:line 154
Inner exception:
Could not load file or assembly 'Microsoft.AnalysisServices.Common.FrontEnd, Version=15.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.
   at BIDSHelper.SSAS.TabularSyncDescriptionsPlugin..ctor(BIDSHelperPackage package)
`

**Comment by furmangg** [comment]
I believe this is the same issue as here: https://github.com/BIDeveloperExtensions/bideveloperextensions/issues/56#issuecomment-463930175

Can you confirm what SSDT version you are running? We are still waiting for a new SSDT to come out to fix this.

**Comment by maddoc1** [comment]
I'm running VS 15.9.10, and SSDT 15.9.0

I have the same problem on other machine that is running VS 15.8.7, SSDT 15.7.1
and another machine VS 15.7.6, SSDT 15.7.1
![image](https://user-images.githubusercontent.com/7616746/55077756-332c2a80-50a1-11e9-87ff-3df954c209c3.png)

**Comment by mattcushing** [comment]
@dgosbell - yeah, I understand it's backward.  Trying to get them to come around to using project model instead :).  I played around with it and the first thing I noticed was not being able to see the error when a job failed.  Had to find it on a report.  Guess it's a change in perspective, but that seems like a pain.

**Comment by furmangg** [comment]
Matt can you scroll down in the About Microsoft Visual Studio window and confirm you see Analysis Services? If not can you change the SSDT install to install Analysis Services in addition to Integration Services in SSDT. Most features work with just part but not all of SSDT installed but it is possible this feature needs some work to cover that scenario

**Comment by mattcushing** [comment]
@dgosbell - changing to package deployment worked, thanks.
@furmangg - I have SSIS and SSAS installed.  What I was speaking of in my last comment pertained to being able to see the fails once the packages are deployed on the SSIS server after execution.  Right now, when they're stored in MSDB, if I view history on the SQLAgent job, I can see what failed.  When they're stored in SSIS catalog, it tells me to view the report to see the failure.  Not sure I have the catalog in my test env set up properly so that might be an issue.

**Comment by furmangg** [comment]
I'm happy to announce we just released BI Developer Extensions v2.3.0 which is compatible with the latest SSDT for Visual Studio 2017. 

In Visual Studio 2017 under the Tools... Extensions and Updates menu and the Update tab you should see v2.3.0 show up. It should auto-update or you can manually update it.

Please create a new issue if you find that anything isn't working as expected.

Ensure you have the latest version of [SSDT installed](https://docs.microsoft.com/en-us/sql/ssdt/download-sql-server-data-tools-ssdt?view=sql-server-2017) (version 15.9.0 or higher) for Visual Studio 2017. Then in Visual Studio 2017 go to Tools... Extensions and Updates... Updates tab... then ensure you install any updates to Microsoft Analysis Services Projects, Microsoft Reporting Services Projects, or Microsoft Integration Services Projects. This release is designed to work with version 2.8.11 SSAS extension or higher, version 2.5.6 SSRS extension or higher, and 2.1 SSIS extension or higher.

**Comment by furmangg** [comment]
If anyone is beta testing, I uploaded a new beta release installer to the link mentioned above.
