### ISSUE TITLE
Unable to load BIDS Helper

### ISSUE THREAD

**Issue by BillBoroson** [BIDeveloperExtensions/bideveloperextensions#59]
My installation of BI Developer Extensions is no longer loading correctly when starting Visual Studio 2017.  If I go to the BIDS Helper Version page on the Tools -> Options menu, I see an error message:

"Could not load file or assembly 'Microsoft.AnalysisServices, Version=15.15.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified."

I only have SSIS installed, not SSAS or SSRS.  Is SSAS now a required component? The full error message is attached.  I tried uninstalling and reinstalling which didn't work.  Anyone else seen this or know how to fix it?  

[BIDS Helper Error Message.txt](https://github.com/BIDeveloperExtensions/bideveloperextensions/files/3086662/BIDS.Helper.Error.Message.txt)

**Comment by furmangg** [comment]
If you go to Tools... Extensions and Updates do you have SSIS extension version 2.1 or 2.2? Are there any BI Developer features for SSIS that aren’t working as you expect? Or are you just concerned with the error messages you posted. Those errors are currently expected if you don’t have SSAS, SSIS and SSRS all installed. We are working on handling this better in future releases. For now there are a few features that won’t work right without all three extensions installed but most will work. Honestly we haven’t tested very completely when not all three extensions are installed.

**Comment by BillBoroson** [comment]
Mine says 2.3.  The one feature I use the most is the SSIS Variables Window Extensions.  But that is not visible on the variables toolbar any more.  Same with the Parameter Window Extensions.

**Comment by debdicken** [comment]
I am having the exact same issue. I first noticed it yesterday afternoon and have tried everything to get VS/SSDT/BIDS working again. Including a complete uninstall/reinstall. I believe there is a versioning issue somewhere between VS, SSDT and BIDS Helper. Can you tell me what the currently supported versions of each are?

**Comment by furmangg** [comment]
@debdicken See the "Ensure you" paragraph here:
https://bideveloperextensions.github.io/downloads/

Please check the individual extension versions and upgrade if they don't match

Do you have all three (SSAS, SSIS, and SSRS) extensions installed?

Which feature specifically isn't working for you?

**Comment by debdicken** [comment]
I have that link and am in the process of reinstalling VS2017 from scratch. I wasn't sure if the info in that link was up to date - so thank you for confirming as such.
Before this issue started (yesterday), I did have all three extensions installed. They were installed via the SSDT standalone installer over a year ago and I use VS/SSDT/BIDS daily.
Yesterday, when I tried to do a smart diff on a SSIS package, I got the exact error that BillBoroson posted at the start of this thread.
I then went to VS Tools->Options to view the settings for BIDS and make sure it wasn't disabled.  It displayed the message "BIDS Helper encountered an error when Visual Studio started:
Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information" and included a rather large stack dump (attached).
I then tried to reinstall SSDT and something corrupted my VS install.
So here I am starting from scratch.
[BIDSError.txt](https://github.com/BIDeveloperExtensions/bideveloperextensions/files/3090938/BIDSError.txt)

**Comment by furmangg** [comment]
@BillBoroson when you say 2.3 do you mean BI Developer Extensions version or the SSIS version. I was expecting the SSIS version to say 2.1 or 2.2.

**Comment by furmangg** [comment]
@debdicken don't assume SSDT got corrupted. This is just BI Developer Extensions looking for the latest SSDT. Just make sure you install the versions I mentioned above and you should hopefully be good.

Which extensions in SSDT do you install? For Smart Diff to work I think you have to have SSAS and SSIS both installed at the moment. We're working on making sure all features work even when certain SSDT extensions are not installed.

**Comment by BillBoroson** [comment]
BI Developer Extensions version.
![BIDevExVersion](https://user-images.githubusercontent.com/18312540/56366290-ccda8980-61c0-11e9-8cc8-363c92f4c70c.png)

**Comment by debdicken** [comment]
> @debdicken don't assume SSDT got corrupted. This is just BI Developer Extensions looking for the latest SSDT. Just make sure you install the versions I mentioned above and you should hopefully be good.
> 
> Which extensions in SSDT do you install? For Smart Diff to work I think you have to have SSAS and SSIS both installed at the moment. We're working on making sure all features work even when certain SSDT extensions are not installed.

I am good to go now, after a full re-install. I am currently running the following:
1. Installed VS 2017 15.9.11 with Workloads: 
- .Net desktop development
- ASP.Net and web development
- Did NOT select Data storage and processing

2.Installed SSDT 15.9 (standalone installer) from https://docs.microsoft.com/en-us/sql/ssdt/download-sql-server-data-tools-ssdt?view=sql-server-2017

3. Rebooted. Checked for updates in Extensions and Updates
- Updated SSAS to 2.8.11
- Updated SSRS to 2.5.6
- SSIS was already at 2.2

**Comment by furmangg** [comment]
@debdicken Thanks so much for documenting this step-by-step. Glad this solved the problem!

**Comment by furmangg** [comment]
We have released a beta release which fixes the issues identified in this thread. You shouldn't get ugly error messages in the Tools... Options... BIDS Helper... Version screen as long as you've got the latest SSDT installed and have updated any SSAS/SSIS/SSRS extensions individually (like @debdicken documented above). You don't have to have all 3 SSAS/SSIS/SSRS extensions installed for the expected BI Developer Extensions features to work as expected. This has been fully tested and fixed up now.

We plan to allow the week of 2019-04-22 for beta testing before releasing this to the public. Please download the release from here and please read the release notes there:
https://github.com/BIDeveloperExtensions/bideveloperextensions/releases/tag/v2.3.0_beta

I'm going to close this thread for now. Feel free to continue to comment on it or start a new thread if the feedback is on a different topic. We appreciate everyone's time in beta testing this release.

**Comment by furmangg** [comment]
If anyone is beta testing, I uploaded a new beta release installer to the link mentioned above.
