### ISSUE TITLE
VS2017 crashes with enabled variable enhancement

### ISSUE THREAD

**Issue by xytras2305** [BIDeveloperExtensions/bideveloperextensions#61]
**Describe the bug**
When the option "Variable window extension" is set to true, VS22017 crashed

**Version**
Take a screenshot of the Tools... Options... BIDS Helper... Version screen and post it here.
![image](https://user-images.githubusercontent.com/50105754/56894738-08aa0480-6a87-11e9-87fc-cec81e81bc79.png)

**To Reproduce**
1. Open Visual Studio
2. Open any ssis packages
3. Open the Variables Tab

**Expected behavior**
No crash, working like before the update to 2.3.1.0

**Screenshots**
![image](https://user-images.githubusercontent.com/50105754/56894833-70f8e600-6a87-11e9-8000-e003de53102f.png)

![image](https://user-images.githubusercontent.com/50105754/56894858-8110c580-6a87-11e9-8091-19b430b30311.png)

**Additional context**
No

**Comment by furmangg** [comment]
Thanks for reporting. 

Note the “please upgrade...” message in the first screenshot. Please go to Tools... Extensions and Updates and update both SSAS and SSRS. Please let us know if that fixes things. It should.

**Comment by xytras2305** [comment]
Unfortunately not. With the actual versions of all extensions, the datasources of ssis package deployment projects are not supported anymore. Only the install of SSDT 15.8.0 and the bids helper 2.2.1 helped. So I deactivated all automatic updates for right now.

**Comment by furmangg** [comment]
Got it. Thanks for the update. I'm glad you were able to work out the right combinations of extensions to get this working and get auto updates enabled. Thanks for confirming
