### ISSUE TITLE
Error when opening properties of an SSIS project

### ISSUE THREAD

**Issue by JornJorCon** [BIDeveloperExtensions/bideveloperextensions#64]
This is my error when trying to open properties of an SSIS project. Worked fine until a few hours ago. (I guess when the updated version was installed automatically...)

---------------------------

---------------------------
Object reference not set to an instance of an object.

   at BIDSHelper.SSIS.DeployPackagesPlugin.cmdButtonProperties_Click(CommandBarButton Ctrl, Boolean& CancelDefault) in C:\projects\BIDS Helper\GitHub\bideveloperextensions\SSIS\DeployPackagesPlugin.cs:line 515
---------------------------
OK   
---------------------------
![image](https://user-images.githubusercontent.com/50144517/56968128-e38ac400-6b62-11e9-8a7f-9949606a3392.png)
![image](https://user-images.githubusercontent.com/50144517/56968181-fa311b00-6b62-11e9-96fd-76df2fada03f.png)

**Comment by furmangg** [comment]
Can you go to Tools... Options... BIDS Helper... Version and include a screenshot there?

I've got the object reference error fixed and checked in but that doesn't mean the feature will work yet. I want to see what versions of SSAS/SSIS/SSRS extensions you have installed and that screen above will tell us.

**Comment by JornJorCon** [comment]
Thanks for the quick response!

![image](https://user-images.githubusercontent.com/50144517/56981497-4e49f880-6b7f-11e9-948d-5dbd2a237d06.png)

**Comment by furmangg** [comment]
I believe I've got this issue fixed. Can you try this debug build to confirm? If you uninstall BI Developer Extensions then download, unzip and install the following I believe the properties pane will properly show the BIDS Helper pane now.

https://github.com/BIDeveloperExtensions/bideveloperextensions/files/3134822/BI.Developer.Extensions.2.3.1_patchedv2.for.VS2017.vsix.zip

**Comment by JornJorCon** [comment]
Hi, I believe that it has been solved indeed! Thanks for the support!!

**Comment by furmangg** [comment]
Release 2.3.2 includes this fix.
