### ISSUE TITLE
Exception on SSIS package - Parameters tab

### ISSUE THREAD

**Issue by AndyDira** [BIDeveloperExtensions/bideveloperextensions#66]
Open new or existing SSIS Package from SSIS Project, switch to Parameters tab.
Observing the following exception error message:

------------------------------

Unable to cast object of type 'ParameterGridControl' to type 'Microsoft.SqlServer.Management.UI.Grid.DlgGridControl'. (Microsoft Visual Studio)

====
Program Location:

   at BIDSHelper.SSIS.ParametersWindowManager.SetupControl() in C:\projects\BIDS Helper\GitHub\bideveloperextensions\SSIS\ParametersWindowPlugin.cs:line 202
   at BIDSHelper.SSIS.ParametersWindowManager.editorWindow_ActiveViewChanged(Object sender, EventArgs e) in C:\projects\BIDS Helper\GitHub\bideveloperextensions\SSIS\ParametersWindowPlugin.cs:line 165
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at Microsoft.DataWarehouse.Design.EditorWindow.OnActiveViewChanged(EventArgs e)
   at Microsoft.DataTransformationServices.Design.DtsPackageView.OnActiveViewChanged(EventArgs args)

-----

When switch back to Control Flow tab and back to Parameters tab - exception does not fire.
Add new parameter, hit "Find Parameter References" button. Observe the following exception error message:  

-----
Object reference not set at instance of an object.
at BIDSHelper.SSIS.ParameterWindowManager.FindReferenceButtonClick() in C:\projects\BIDS Helper\GitHub\bidsdeveloperextensions\SSIS\ParameterWindowsPlugin.cs:line 231

------------------------------

Influence - intermittent error messages on Parameters tab, cannot trace selected parameter dependence.

**Version**
----
Microsoft Visual Studio Community 2017 
Version 15.9.11
VisualStudio.15.Release/15.9.11+28307.586
Microsoft .NET Framework
Version 4.7.03062

Installed Version: Community

Visual C++ 2017   00369-60000-00001-AA046
Microsoft Visual C++ 2017

AnkhSVN - Subversion Support for Visual Studio   2.7.12815.35086
AnkhSVN - Subversion Support for Visual Studio 2.7.12815.35086 
 * Ankh.Package 2.7.12815.35086
 * Subversion 1.9.5 via SharpSvn 1.9005.3940.224
 * Git/LibGit2 0.24.0 via SharpGit 0.2401.1116.230

SharpSvn is linked to: Apr 1.5.2, Apr-util 1.5.4, Cyrus Sasl 2.1.26, eXpat 2.2.0, LibSSH2 1.8.0, OpenSSL 1.0.2k  26 Jan 2017, Serf 1.3.9, SQLite 3.17.0, Subversion 1.9.5-SharpSvn, Utf8proc 1.1.5, ZLib 1.2.8
SharpSvn is optionally linked to: Berkeley DB 4.4.20, SharpPlink 0.67.0(SharpSvn)

SharpGit is linked to: Apr 1.5.1, Apr-Util 1.5.4, eXpat 2.1.0, Libgit2 0.24.0, LibSSH2 1.7.0, OpenSSL 1.0.2h  3 May 2016, Subversion 1.9.3, Utf8proc 1.1.5, ZLib 1.2.8

Application Insights Tools for Visual Studio Package   8.14.20131.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.9.04012.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   15.8.31590
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.61435.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.9.03024.0
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   15.9.03024.0
Azure Functions and Web Jobs Tools

BI Developer Extensions for Visual Studio 2017   2.3.2
BI Developer Extensions v2.3.2 for Visual Studio 2017 - An add-in to extend SQL Server Data Tools

BimlExpress   1.0
BimlExpress is a Visual Studio extension for editing and building Biml files.

C# Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP Project System   2.0
JavaScript UWP Project System

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.0.0

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   1.0
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

MLGen Package Extension   1.0
MLGen Package Visual Studio Extension Detailed Info

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Project   1.0
Information about my package

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Redgate SQL Change Automation   3.0.19120.7245
Extend DevOps processes to your SQL Server databases and safely automate database deployments.

Visit https://www.red-gate.com/sca/productpage for more information.

Copyright (C) 2011 Red Gate Software Ltd. All rights reserved.

This software contains components from Component Owl.
SQL Server is a registered trademark of Microsoft Corporation.
Visual Studio is a registered trademark of Microsoft Corporation.

SQL Change Automation contains code from the following open source software:

NuGet https://www.nuget.org/
SQL LocalDB Wrapper https://github.com/martincostello/sqllocaldb
Autofac https://autofac.org/
Json.NET https://json.net/
MahApps.Metro http://mahapps.com/
SemVer https://github.com/maxhauser/semver
Log4Net http://logging.apache.org/log4net/
StringTemplate https://github.com/antlr/stringtemplate4
Extended WPF Toolkit https://wpftoolkit.codeplex.com/
Code InfoBox VSX http://www.codeproject.com/Articles/55196/Code-InfoBox-Visual-Studio-Extension-VSX
OctoPack https://github.com/OctopusDeploy/OctoPack
SQLite https://sqlite.org/

This product contains icons from http://www.visualpharm.com distributed under a free backlink license.

For license details or other notices relating to the above software, please see NOTICE.TXT and EULA.rtf in the SQL Change Automation application folder.
    

Redgate SQL Prompt   9.2.8.6358
Write, format, and refactor SQL effortlessly

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

SQL Server Analysis Services   15.0.1331.137
Microsoft SQL Server Analysis Services Designer 
Version 15.0.1331.137

SQL Server Data Tools   15.1.61903.01040
Microsoft SQL Server Data Tools

SQL Server Integration Services   
Microsoft SQL Server Integration Services Designer
Version 15.0.1100.123

SsmsVsIntegration   1.0
Information about my package

TypeScript Tools   15.9.20918.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.2 for F# 4.5   15.8.0.0.  Commit Hash: 6e26c5bacc8c4201e962f5bdde0a177f82f88691.
Microsoft Visual F# Tools 10.2 for F# 4.5

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Universal Windows Apps   15.0.28307.556
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

WiX Toolset Visual Studio Extension   0.9.21.62588
WiX Toolset Visual Studio Extension version 0.9.21.62588
Copyright (c) .NET Foundation and contributors. All rights reserved.

===

**Expected behavior**
No exception error messages, function "Find Parameter Reference" is working.

**Comment by furmangg** [comment]
Thanks for reporting this. Can you go to Tools... Options... BIDS Helper... Version. Can you screenshot and upload here? If it suggests you upgrade anything can you look into that?

Once I get a confirmation you are on the latest SSDT extension versions I can debug this better.

**Comment by AndyDira** [comment]
Below is the screenshot of BIDS Helper Version tab  

![2019-05-07 17_26_02-192 168 16 9 — Подключение к удаленному рабочему столу](https://user-images.githubusercontent.com/50011976/57307309-00883f80-70ed-11e9-8607-9f62871bcbc0.png)

**Comment by furmangg** [comment]
If I follow the issue report, initially you didn't have the SSRS extension installed but now you do. I don't suspect that makes a difference but I'll ask anyway. Did that resolve the issue?

**Comment by furmangg** [comment]
If you install the latest version (2.3.3) it should fix this issue. Please allow the extension to auto-update or install manually and let me know if the problem isn't resolved now. Thanks for reporting and thanks for your patience.
