### ISSUE TITLE
vs 2017 Could not load file or assembly

### ISSUE THREAD

**Issue by ShlyahtinDN** [BIDeveloperExtensions/bideveloperextensions#67]
**Describe the bug**
---------------------------
BIDS Helper - Error
---------------------------
Could not load file or assembly 'Microsoft.DataWarehouse.VsIntegration.AS, Version=15.2.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. Не удается найти указанный файл.

   at BIDSHelper.SSAS.NonDefaultPropertiesPlugin.ExecAS(Project p)

   at BIDSHelper.SSAS.NonDefaultPropertiesPlugin.Exec() in C:\projects\BIDS Helper\GitHub\bideveloperextensions\SSAS\NonDefaultPropertiesPlugin.cs:line 166
---------------------------
ОК   
---------------------------

**Version**
2.3.2

**Additional context**
Plugin cannot boot

**Comment by furmangg** [comment]
Please to go Tools... Options... BIDS Helper... Version

Can you post a screenshot here?

If it suggests you update SSDT please do

**Comment by ShlyahtinDN** [comment]
Good day. I now see what needs to be done.

вт, 14 мая 2019 г. в 14:38, Greg Galloway <notifications@github.com>:

**Comment by ShlyahtinDN** [comment]
But the studio does not offer to update these components.

вт, 14 мая 2019 г. в 14:38, Greg Galloway <notifications@github.com>:

**Comment by ShlyahtinDN** [comment]
![vs](https://user-images.githubusercontent.com/50585297/57704149-07bdc900-766a-11e9-8062-3c35af25e57c.PNG)
![upd](https://user-images.githubusercontent.com/50585297/57704163-0be9e680-766a-11e9-9986-f1d06c7c93fb.PNG)
![ssas](https://user-images.githubusercontent.com/50585297/57704169-0ee4d700-766a-11e9-91b1-529aa0158dc6.PNG)

**Comment by furmangg** [comment]
You are way old on SSDT versions. You could try an old BI Developer Extensions release and then immediately mark it not to auto-update. 
https://github.com/BIDeveloperExtensions/bideveloperextensions/releases/tag/v2.2.1

But I would recommend downloading the latest SSDT installer and running it. This version is compatible with the latest BI Developer Extensions:
https://docs.microsoft.com/en-us/sql/ssdt/download-sql-server-data-tools-ssdt?view=sql-server-2017

**Comment by furmangg** [comment]
Did you decide which direction you're going to go (update SSDT or downgrade BI Developer Extensions)?

**Comment by ShlyahtinDN** [comment]
Hello. I decided to downgrade to BI Developer Extensions. It works. Thank you very much!
