### ISSUE TITLE
Can't install in VS 2019

### ISSUE THREAD

**Issue by ASk1** [BIDeveloperExtensions/bideveloperextensions#68]
BIDS extension cannot be found in 

I downloaded BI.Developer.Extensions.2.3.2.for.VS2019.vsix from 
https://marketplace.visualstudio.com/items?itemName=BIDSHelper.BIDeveloperExtensionsVS2019

This extension is not installable on any currently installed products.
 
From log file

24.05.2019 10:55:04 - Searching for applicable products...
24.05.2019 10:55:04 - Found installed product - Global Location
24.05.2019 10:55:04 - Found installed product - ssms
24.05.2019 10:55:04 - Found installed product - Visual Studio Professional 2017
24.05.2019 10:55:04 - Found installed product - Visual Studio Professional 2019
24.05.2019 10:55:04 - Found installed product - Visual Studio Build Tools 2017 (2)
24.05.2019 10:55:05 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by furmangg** [comment]
Can you open Visual Studio 2019 and go to the Help... About Microsoft Visual Studio menu the. Click the Copy button and paste that info here. And also screenshot that page and upload that screenshot here. 

Close the About screen and do you see any offers of Visual Studio updates? Do you maybe have a prerelease version installed?

**Comment by ASk1** [comment]
Microsoft Visual Studio Professional 2019
Version 16.1.0
VisualStudio.16.Release/16.1.0+28917.181
Microsoft .NET Framework
Version 4.7.03190

Installed Version: Professional

Microsoft Visual Studio Tools for Applications 2019   00435-60000-00000-AA273
Microsoft Visual Studio Tools for Applications 2019

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASP.NET and Web Tools 2019   16.1.429.50124
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.1.429.50124
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.1.429.50124
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.3.9000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Stream Analytics Tools for Visual Studio   2.3.9000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   3.1.0-beta4-19266-03+9d80dea7fe1b14043b9b2ac4d0b59ed26f508742
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

GitHub.VisualStudio   2.9.1.7781
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

Microsoft Azure HDInsight Azure Node   2.3.9000.0
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.3.9000.0
Language service for Hive query

Microsoft Azure Stream Analytics Language Service   2.3.9000.0
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 0x10 - v2.9.20419.2

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   1.0
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

NuGet Package Manager   5.1.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Project   1.0
Information about my package

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Redgate SQL Search   3.2.6.2313
Search functionality for SQL Server databases, from within Visual Studio

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

SQL Server Analysis Services   15.0.1331.137
Microsoft SQL Server Analysis Services Designer 
Version 15.0.1331.137

SQL Server Data Tools   16.0.61904.23160
Microsoft SQL Server Data Tools

SQL Server Integration Services   15.0.1300.375
Microsoft SQL Server Integration Services Designer
Version 15.0.1300.375

SQL Server Reporting Services   15.0.1331.137
Microsoft SQL Server Reporting Services Designers 
Version 15.0.1331.137

SsmsVsIntegration   1.0
Information about my package

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   16.0.10506.2004
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.1.0-beta4-19266-03+9d80dea7fe1b14043b9b2ac4d0b59ed26f508742
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

**Comment by ASk1** [comment]
![image](https://user-images.githubusercontent.com/2006065/58325933-0a6fa980-7e34-11e9-968c-ad4eed4d1cf7.png)

**Comment by ASk1** [comment]
All updates installed as of latest version 16.1.0
https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes#16.1.0

And latest exSSDTBI extensions from marketplace: SSAS, SSRS, SSIS

**Comment by ASk1** [comment]
![image](https://user-images.githubusercontent.com/2006065/58329721-e44f0700-7e3d-11e9-9944-60a7dc86957c.png)

**Comment by ASk1** [comment]
Same issue with  latest version 16.1.0

**Comment by furmangg** [comment]
If you open VS2019 and look in Extensions... Manage Extensions... do you see BI Developer Extensions installed already?

**Comment by furmangg** [comment]
Can you click View Install Log and save and attach the entire log as an attachment to this thread?

**Comment by ASk1** [comment]
I have installed BIDS 2.3.2 only in VS2017.
In VS2019 there is no installed BIDS and even I can't find it in Online/Visual Studio Marketplace. I downloaded it from https://marketplace.visualstudio.com/items?itemName=BIDSHelper.BIDeveloperExtensionsVS2019 as BI.Developer.Extensions.2.3.2.for.VS2019.vsix and tried to install.  Please find attached log
[dd_VSIXInstaller_20190528112613.log](https://github.com/BIDeveloperExtensions/bideveloperextensions/files/3226334/dd_VSIXInstaller_20190528112613.log)

**Comment by ASk1** [comment]
I've removed VS2019 Professional Trial and installed VS2019 Community with Data Tools and then Integration Project 3.0 Preview extension. Same error when I try to install BIDS 2019

**Comment by furmangg** [comment]
Hmm. Let me dig into the installer tonight and see if I can explain what’s wrong.

**Comment by ASk1** [comment]
Thank you, will wait
Also noticed that in BIDS 2017 expression editor in SSIS variables disappeared

**Comment by furmangg** [comment]
Try waiting 20 seconds after VS start and then clicking into Solution Explorer and then package designer and then variables window. Could be a change we made recently to make our extension load async.

**Comment by furmangg** [comment]
I was able to repro this. Apparently when VS2019 moved from version 16.0 to version 16.1 it broke the installer. We've fixed the version range it can install onto. Please search in the marketplace for BI Developer Extensions and you should find it now and be able to install version 2.3.3.

**Comment by ASk1** [comment]
Thank you, Greg.  It's installed successfully. An as you recommended I wait few second and expression editor icons appeared in variables window in VS 2019. But in VS 2017 it does not appear

**Comment by furmangg** [comment]
@ask1 can you think of anything different with your project in VS2017? (I assume you have a project and didn’t just open a .dtsx file without a project?)

Can you open VS2017... Tools... Options... BIDS Helper... Version... then screenshot it and upload that here. The codebase is nearly identical for our extension between 2017 and 2019. So my best guess is that you may be behind on SSDT updates. If that Version screen suggests you update any extensions please do.

**Comment by ASk1** [comment]
@furmangg, I appreciate your concern and I thank you for your help. Unfortunately we can't move our project to VS2019 nor upgrade SSDT in VS2017 because of new Oracle connector - we have to stay with SSDTBI 15.8.0 
https://docs.microsoft.com/en-us/sql/ssdt/release-notes-ssdt?view=sql-server-2017

Please find attached screenshot and error log file.
[VS2017 BIDS error log.txt](https://github.com/BIDeveloperExtensions/bideveloperextensions/files/3235875/VS2017.BIDS.error.log.txt)


![image](https://user-images.githubusercontent.com/2006065/58615827-b85fd580-82c4-11e9-9736-cf931d136670.png)

**Comment by furmangg** [comment]
Oh. Got it. 

Buried in the release notes is the following recommendation for your scenario. 

can't upgrade, then consider installing BI Developer Extensions 2.2.1 instead then disabling "automatically upgrade this extension" in Tools... Extensions and Updates.
https://github.com/BIDeveloperExtensions/bideveloperextensions/releases/tag/v2.2.1

Let me know if that works.

**Comment by furmangg** [comment]
I just reached out to the SSIS team and confirmed since 15.9.0 that Oracle is working again. There are some early adopter issues but it is supported. 
https://techcommunity.microsoft.com/t5/SQL-Server-Integration-Services/Microsoft-Connector-for-Oracle-is-released-for-SQL-Server-2019/ba-p/565923

So if you prefer that approach (upgrading SSDT vs. downgrading BI Developer Extensions) feel free

**Comment by ASk1** [comment]
@furmangg  Thank you very much. Switched off my network connection, installed 2.2.1 version and disabled auto update. With this version the expression editor works.

Unfortunately 15.9.0 and later oracle connector still doesn't work in dataflow with all but one our servers and I can't identify the problem. Posted comment on mentioned article.
