### ISSUE TITLE
unused columns report

### ISSUE THREAD

**Issue by miladmyled** [BIDeveloperExtensions/bideveloperextensions#71]
I get this error

method not found microsoft.analysisservices.backend.idatamodelingtablecollection
microsft.analysisservices.backend.datamodelingsandbox.get_tables()

**Comment by furmangg** [comment]
What compatibility level of SSAS? Can you screenshot the Tools... Options... BIDS Helper... Version screen and upload here? If it suggests you upgrade SSDT please do that unless there is a reason you can’t.

**Comment by miladmyled** [comment]
Hi
Thanks for the prompt response
I am trying to use it in VS 14.0.25431.01 update 3
SSAS Tabular project
[image: Untitled.png]

[image: Untitled2.png]


میلاد فیروزی

کارشناس هوش تجاری
<https://ir.linkedin.com/in/miladfirouzi?trk=profile-badge-cta>
<http://www.digikala.com>

**Comment by furmangg** [comment]
You may have to upload those sceeenshot images to the website. Your email reply didn’t preserve them

**Comment by miladmyled** [comment]
Sure
will do ASAP

میلاد فیروزی

کارشناس هوش تجاری
<https://ir.linkedin.com/in/miladfirouzi?trk=profile-badge-cta>
<http://www.digikala.com>

**Comment by miladmyled** [comment]
![Untitled2](https://user-images.githubusercontent.com/30826499/59190684-97379880-8b92-11e9-8adf-bf655b267ef6.png)
![Untitled](https://user-images.githubusercontent.com/30826499/59190685-97d02f00-8b92-11e9-873c-9f9ca05bd061.png)

**Comment by furmangg** [comment]
What compatibility level of SSAS? Can you screenshot the Tools... Options... BIDS Helper... Version screen and upload here? If it suggests you upgrade SSDT please do that unless there is a reason you can’t.

**Comment by miladmyled** [comment]
![image](https://user-images.githubusercontent.com/30826499/59191332-7708d900-8b94-11e9-8353-b818ca9f6dd7.png)

**Comment by miladmyled** [comment]
what shall i do?

**Comment by furmangg** [comment]
Looks like you don't have the latest SSDT. I would go to the following link and install 17.4 for Visual Studio 2015 and see if that resolves the issue with the unused columns report. (You can ignore the Codeplex error in the Version screenshot above.)

https://docs.microsoft.com/en-us/sql/ssdt/previous-releases-of-sql-server-data-tools-ssdt-and-ssdt-bi?view=sql-server-2017
