### ISSUE TITLE
SSDT schema comparison does not work anymore

### ISSUE THREAD

**Issue by AdamWilbur** [BIDeveloperExtensions/bideveloperextensions#72]
**Describe the bug**
SSDT schema comparison does not work anymore

**Version**
Take a screenshot of the Tools... Options... BIDS Helper... Version screen and post it here.
![image](https://user-images.githubusercontent.com/29470429/59887288-a202e200-9377-11e9-8489-5576f440905a.png)

**To Reproduce**
1.  Tools>>SQL Server>> New Schema Comparison
2.  Select a source (database)
3.  Select a target (database)
4.  Click compare
5.  Get error:
Severity	Code	Description	Project	File	Line	Suppression State
Error		Value cannot be null.
Parameter name: identifierGroup			0	

**Expected behavior**
Compare should work

**Screenshots**

**Additional context**

**Comment by furmangg** [comment]
Unless you are saying that it works when BI Developer Extensions is disabled then this is not the forum to report that bug. I would look here for options to report to Microsoft:
https://docs.microsoft.com/en-us/sql/ssdt/download-sql-server-data-tools-ssdt?view=sql-server-2017#info_tip-get-help
