### ISSUE TITLE
Edit Aggregations crashes Visual Studio Community 2019

### ISSUE THREAD

**Issue by ChrisHChrisH** [BIDeveloperExtensions/bideveloperextensions#73]
Selecting Edit Aggregations on a cube causes Visual Studio to crash and restart showing banner message "A previous session ended unexpectedly. Disabling the extension Microsoft Analysis Services Projects 2.8.15 might help."

Also, selecting Dimension Health Check on a dimension displays a small dialog box with the message "Entry point was not found".

Environment is Visual Studio Community 2019 with the following options and extensions:
ASP.NET and web development
.NET desktop development
Data storage and processing
BI Developer Extensions for Visual Studio 2019 version 2.3.3
Microsoft Analysis Services Projects version 2.8.15
Microsoft Reporting Services Projects version 2.5.8
SQL Server Integration Services Projects version 3.1

These issues occur with pre-existing and newly created Analysis Services projects.

Take a screenshot of the Tools... Options... BIDS Helper... Version screen and post it here.
![image](https://user-images.githubusercontent.com/53053132/61471860-67db2f00-a97b-11e9-8989-7b91b6a2c461.png)

**Comment by furmangg** [comment]
Thanks for reporting. Yes, it looks like they updated the SSAS extension recently and it is going to be some work to bring BI Developer Extensions back to compatibility with it. I'm in the middle of testing a beta build and will keep this thread posted.

**Comment by furmangg** [comment]
I've just published BI Developer Extensions 2.3.4 for Visual Studio 2019. Try that out and I believe it should fix the issue you're seeing for the SSAS extension version you're using (the latest).

**Comment by ChrisHChrisH** [comment]
Version 2.3.4 is working now, with Microsoft Analysis Services Projects version 2.8.17 (updated automatically from 2.8.15 before tested!).
Thanks for the quick turnaround.
