### ISSUE TITLE
Update All Estimate Counts button missing -- Multidimensional

### ISSUE THREAD

**Issue by cosminioan** [BIDeveloperExtensions/bideveloperextensions#77]
hi folks, I am using version 2.3.4 for VS DataTools 2017 and it seems to be working beautifully on my multidimensional project  -- many thanks for the tool.

I am trying to get the Updated Estimated Counts but the buttons are missing.
I've uninstalled and re-installed BIDS Helper but to no avail.
My VS DataTools version is 15.9.16 and Analysis Services 15.0.1483.0

Funny thing,  it seems to be working fine on another computer. so not sure what's going on.

Screenshot with missing buttons, after the first 3:
![image](https://user-images.githubusercontent.com/14153647/64885254-a1ee4780-d631-11e9-8f8c-7fc0b475d6de.png)

All other BIDS Helper functionality seems to be working as expected, except these buttons.

Am I missing anything obvious?
many thanks,
Cos

**Comment by furmangg** [comment]
Thanks for reporting Cos. It looks like a new version of the SSAS extension (v. 2.8.18 from the Tools... Extensions and Updates dialog) got release within the last week which may have broken a few things. We'll work to get this and other features fixed.

**Comment by cosminioan** [comment]
that's correct, it appears that 2.8.17 is working fine.  I can probably downgrade back to that version if it's a big issue to fix, no biggie.  :-)

many thanks for the feedback, Greg

**Comment by furmangg** [comment]
We just released v2.3.5 of BI Developer Extensions which resolves the problem. Please go to the manage Extensions window and ensure you install the update to BI Developer Extensions (and the other SSDT extensions, too). Thanks for your patience. Please let us know if this doesn't resolve your issue.
