### ISSUE TITLE
Deploy mdx script fails in Visual Studio 2017 (Version 15.9.16)

### ISSUE THREAD

**Issue by ihadx** [BIDeveloperExtensions/bideveloperextensions#78]
When I try to deploy the MDX script of an SSAS project targeting SQLServer 2016 SP1 I receive the following error message:

Could not load type 'Microsoft.AnalysisServices' from assembly 'Microsoft.DataWarehouse.VsIntegration.AS, Version=15.5.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91'.

The complete error message is shown on the attached screenshot.
![image](https://user-images.githubusercontent.com/55699033/65428081-f9e83380-de13-11e9-9188-1ea0a9fb215e.png)

SSAS / Analysis services project extension version: 2.8.19
Microsoft SQL Server Data Tools for Visual Studio 2017 (SSDT) Version 15.9.16
BI Developer Extensions for Visual Studio: Version 2.3.4
SSAS Project target version: SQL Server 2016 SP1

![image](https://user-images.githubusercontent.com/55699033/65428060-f3f25280-de13-11e9-9540-1e41eeb3c376.png)

**Comment by furmangg** [comment]
We just released v2.3.5 of BI Developer Extensions which resolves the problem. Please go to the manage Extensions window and ensure you install the update to BI Developer Extensions (and the other SSDT extensions, too). Thanks for your patience. Please let us know if this doesn't resolve your issue.
