### ISSUE TITLE
Microsoft Analysis Project Extension for Visual Studio 2019 does not work on Windows 7 OS

### ISSUE THREAD

**Issue by ch1922** [BIDeveloperExtensions/bideveloperextensions#79]
The Microsoft Analysis Project Extension for Visual Studio 2019 does not work on Windows 7 OS. 

The Version of the Extension is 2.9.1

The error happens when trying to install the extension from the Market Place after downloading it and running under an Administrator account

The Extension should install without issues

From the Log, this is a sample of the error:

10/3/2019 12:07:51 PM - Beginning to install extension to Visual Studio Enterprise 2019...
10/3/2019 12:07:53 PM - Failed to get profile list from registry.
10/3/2019 12:08:20 PM - Skipping non-applicable package Microsoft.Windows.UniversalCRT.Msu.8: The current OS Version '6.1.7601.65536' is not in the supported version range '[6.2,6.3)'.
10/3/2019 12:08:20 PM - Skipping non-applicable package Microsoft.Windows.UniversalCRT.Msu.81: The current OS Version '6.1.7601.65536' is not in the supported version range '[6.3,6.4)'.
10/3/2019 12:08:20 PM - Skipping non-applicable package Microsoft.VisualStudio.AspNet45.Feature: The current OS Version '6.1.7601.65536' is not in the supported version range '6.2'.
10/3/2019 12:08:20 PM - Skipping non-applicable package Microsoft.Ancm.IIS.Msi: Required conditions are not satisfied: IISCoreWebEngineInstalledx64 And IISW3SvcInstalledx64
10/3/2019 12:08:20 PM - Skipping non-applicable package Microsoft.Ancmv2.IIS.Msi: Required conditions are not satisfied: IISCoreWebEngineInstalledx64 And IISW3SvcInstalledx64
10/3/2019 12:08:20 PM - Skipping non-applicable package Microsoft.Net.4.6.2.TargetingPack.Resources: The current OS Version '6.1.7601.65536' is not in the supported version range '10.0.14393'.
10/3/2019 12:08:20 PM - Skipping non-applicable package Microsoft.Net.4.6.2.TargetingPack: The current OS Version '6.1.7601.65536' is not in the supported version range '10.0.14393'.
10/3/2019 12:08:20 PM - Skipping non-applicable package Microsoft.Azure.PowerShell: The current OS Version '6.1.7601.65536' is not in the supported version range '6.2'.
Required conditions are not satisfied: Not Powershell5
10/3/2019 12:08:20 PM - Skipping non-applicable package Microsoft.Azure.PowerShellNew: The current OS Version '6.1.7601.65536' is not in the supported version range '6.2'.
10/3/2019 12:08:20 PM - Skipping non-applicable package Microsoft.VisualStudio.Graphics.EnableTools: The current OS Version '6.1.7601.65536' is not in the supported version range '10.0.10240'.
10/3/2019 12:08:20 PM - Skipping non-applicable package Microsoft.VisualStudio.OfficeDeveloperTools.WIF.WindowsFeature: The current OS Version '6.1.7601.65536' is not in the supported version range '6.2'.
10/3/2019 12:08:20 PM - Skipping non-applicable package Microsoft.Net.4.6.2.SDK: The current OS Version '6.1.7601.65536' is not in the supported version range '10.0.14393'.

**Comment by furmangg** [comment]
This forum is for BI Developer Extensions not for SSDT itself. I’m going to close this issue. 

 Can you update from Windows 7? That OS was released 10 years ago.

**Comment by ch1922** [comment]
OK, Thank You, 

Calin
