### ISSUE TITLE
unable to deploy MDX script (Multidimensional SSAS 2017)

### ISSUE THREAD

**Issue by cosminioan** [BIDeveloperExtensions/bideveloperextensions#82]
**Describe the bug**
hi Darren,
I've tried for the first time to deploy an MDX script, using the  (in SSAS 2017 latest SP), using the BI Developer Extensions, but get the following errors:

![image](https://user-images.githubusercontent.com/14153647/67232658-cba84480-f40f-11e9-8596-bdf656e0e528.png)
![image](https://user-images.githubusercontent.com/14153647/67233001-6d2f9600-f410-11e9-8fd0-c55fed23caa2.png)

BI Developer Extensions for Visual Studio, version 2.3.4
Microsoft Analysis Services Projects 2.8.17
Visual Studio 2017 SSDT 15.9.16

any thoughts on what might be wrong?
many thanks,
Cosmin

**Comment by cosminioan** [comment]
if I open the AdventureWorks EE code, upon attempting to deploy MDX script, the same error occurs in DeployMDXScriptPlugin.cs on line 240 instead of line 261 above.

**Comment by furmangg** [comment]
You can fix the problem by processing the cube on the server
