### ISSUE TITLE
"Deploy MDX stript" button is simply missing

### ISSUE THREAD

**Issue by ibobak** [BIDeveloperExtensions/bideveloperextensions#85]
I don't see the button "Deploy MDX stript"  which was in previous version

**Version**
2.3.4.0
Visual studio 2019 Community

**To Reproduce**
Open a SSAS multidimensional project, open the cube and see this (screenshot):
![2019-11-12 19_54_40-Window](https://user-images.githubusercontent.com/8807043/68692407-7ed70a00-0586-11ea-8ccc-aa9083f54617.png)

**Comment by furmangg** [comment]
We just released v2.3.5 of BI Developer Extensions which resolves the problem. Please go to the manage Extensions window and ensure you install the update to BI Developer Extensions (and the other SSDT extensions, too). Thanks for your patience. Please let us know if this doesn't resolve your issue.
