### ISSUE TITLE
Error when opening a project after installing extension

### ISSUE THREAD

**Issue by MamDevRR** [BIDeveloperExtensions/bideveloperextensions#86]
**Describe the bug**
Error when opening a project- Project loads then after background tasks completion --> connection - guid issue. No project error if extension is disabled or uninstalled.

**Version**
Using VS Ent 2019 version 16.3.7. Extension version: 2.3.4

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by furmangg** [comment]
Please install BI Developer Extensions v2.3.5 and let us know if that doesn't resolve the problem. Honestly, your bug report is a bit thin on details. I'm not sure what a "connection guid issue" is. So please post back if the latest release doesn't solve the problem.
