### ISSUE TITLE
Error when opening SSIS project properties

### ISSUE THREAD

**Issue by slyfur** [BIDeveloperExtensions/bideveloperextensions#87]
**Describe the bug**
When I right-click on an existing SSIS project and select "Properties" I receive the following error:

![image](https://user-images.githubusercontent.com/695565/70173255-19af9980-1698-11ea-949f-3177b1678dcf.png)

**Version**
![image](https://user-images.githubusercontent.com/695565/70173319-3350e100-1698-11ea-8422-01fce103b634.png)

**To Reproduce**
1. Go to SSIS project node.
2. Right-click and select "Properties"
3. See error

Also, once the properties open, there is no section for BIDS Helper.

![image](https://user-images.githubusercontent.com/695565/70173433-68f5ca00-1698-11ea-88ac-a363423bfbba.png)

**Additional context**
All of these projects probably contain older packages that were migrated to newer versions.  I discovered this when trying to use the "Deploy" feature.

**Comment by DocGitHub** [comment]
I have Visual Studio 2017 and 2019 installed, the error only occurs in 2019.
[Offcourse SSIS support has been moved from  SSDT to the extension](https://techcommunity.microsoft.com/t5/sql-server-integration-services/new-delivery-model-for-sql-server-data-tools-in-visual-studio/ba-p/479289).

**Comment by ChrisSwe** [comment]
I think something broke with Visual Studio 16.4. 

ProjectManager is type of DataTransformationsProjectManager instead of DataWarehouseProjectManager

**Comment by furmangg** [comment]
We just released v2.3.5 of BI Developer Extensions which resolves the problem. Please go to the manage Extensions window and ensure you install the update to BI Developer Extensions (and the other SSDT extensions, too). Thanks for your patience. Please let us know if this doesn't resolve your issue.
