### ISSUE TITLE
Keep getting error on SSIS project Properties (freshly installed VSDT 2017 )

### ISSUE THREAD

**Issue by DonatasLTU** [BIDeveloperExtensions/bideveloperextensions#91]
Hi,

Keep getting this error when hitting Properties on SSIS project. BIDS does not work afterwards:

**Unable to cast object of type** **'Microsoft.DataTransformationServices.Project.DataTransformationsProjectManager' to type
'Microsoft.DataWarehouse.Project.DataWarehouseProjectManager'. at BIDSHelper.SSIS.DeployPackagesPlugin.cmdButtonProperties_Click
(CommandBarButton Ctrl, Boolean&CancelDefault) in C:\projects\BIDSHelper\GitHub\bideveloperextensions\SSIS\DeployPackagesPlugin.cs:line 535**

**Version**

Microsoft SQL Server Data Tools for Visual Studio 2017 (SSDT) Version 15.9.20

Extensions:
Microsoft Analysis Services Projects Version 2.9.5
Microsoft Integration Services Projects Version 2.5
Microsoft Reporting Services Projects Version 2.6.3

**To Reproduce**
1. Go to any SSIS project.
2. Click on project and click Properties.
3. See error

**Expected behavior**
I expect to load Project Properties window and could be able to deploy SSIS packages to desired location. 

**Additional context**
This is a totally fresh Microsoft SQL Server Data Tools for Visual Studio 2017 on newly installed Windows 10. Have been using BIDS on windows 7 - always worked as a charm.

**Comment by jbaynhamuk** [comment]
I have the identical behaviour in VS 2017.

I have just installed VS 2019 (16.4.5) to try and workaround this:

SQL Server Data Tools   16.0.62002.03150
SQL Server Integration Services   15.0.2000.71
SQL Server Reporting Services   15.0.1659.0
SQL Server Analysis Services   15.0.1746.0

but am still getting the identical error when trying to open the project properties on an SSIS project (newly created).

**Comment by DonatasLTU** [comment]
Yes. I have also installed VS 2019 Professional ( with a licence) . Still the same error.

**Comment by furmangg** [comment]
We just released v2.3.5 of BI Developer Extensions which resolves the problem. Please go to the manage Extensions window and ensure you install the update to BI Developer Extensions (and the other SSDT extensions, too). Thanks for your patience. Please let us know if this doesn't resolve your issue.

**Comment by DonatasLTU** [comment]
Great, it works, thanks!
