### ISSUE TITLE
BIDS currently not working with VS 16.4.6

### ISSUE THREAD

**Issue by jrhiem** [BIDeveloperExtensions/bideveloperextensions#92]
**Describe the bug**
Most of the tools currently not working with Visual Studio Version 16.4.6. For example in SSAS Project when trying "Non default properties" on a dimension.

![image](https://user-images.githubusercontent.com/62053645/76422972-60531500-63a6-11ea-8c82-560b890dac6d.png)

SSAS Extension Version: 2.9.5
SSRS Extension Version: 2.6.3
SSIS Extension Version: 3.4

**Version**
![image](https://user-images.githubusercontent.com/62053645/76423173-a90ace00-63a6-11ea-8885-c3fa13ed6081.png)

**Comment by furmangg** [comment]
We just released v2.3.5 of BI Developer Extensions which resolves the problem. Please go to the manage Extensions window and ensure you install the update to BI Developer Extensions (and the other SSDT extensions, too). Thanks for your patience. Please let us know if this doesn't resolve your issue.
