### ISSUE TITLE
Biml not found in bar after installing pluging

### ISSUE THREAD

**Issue by AmiraBedhiafi** [BIDeveloperExtensions/bideveloperextensions#94]
I am new to Biml and I recently installed it using Manage Extension in Visual Studio 2019 but cannot find it in the bar.

**Comment by dgosbell** [comment]
As noted in the [documetation](https://bideveloperextensions.github.io/features/BimlPackageGenerator/), Varigence has stopped providing support for the BIML Engine in BI Developer Extensions. They now have their own BimlExpress extension - you might want to try that.
